/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.api;

import com.kcjmowright.schwab.marketdata.model.ErrorResponse;
import com.kcjmowright.schwab.marketdata.model.InlineResponse2001;
import com.kcjmowright.schwab.marketdata.model.InstrumentResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstrumentsApi
 */
@Ignore
public class InstrumentsApiTest {

    private final InstrumentsApi api = new InstrumentsApi();

    /**
     * Get Instruments by symbols and projections.
     *
     * Get Instruments details by using different projections.  Get more specific fundamental instrument data by using fundamental as the projection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstrumentsTest() {
        String symbol = null;
        String projection = null;
        InlineResponse2001 response = api.getInstruments(symbol, projection);

        // TODO: test validations
    }
    /**
     * Get Instrument by specific cusip
     *
     * Get basic instrument details by cusip
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstrumentsByCusipTest() {
        String cusipId = null;
        InstrumentResponse response = api.getInstrumentsByCusip(cusipId);

        // TODO: test validations
    }
}
