/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.api;

import com.kcjmowright.schwab.marketdata.model.ErrorResponse;
import com.kcjmowright.schwab.marketdata.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MoversApi
 */
@Ignore
public class MoversApiTest {

    private final MoversApi api = new MoversApi();

    /**
     * Get Movers for a specific index.
     *
     * Get a list of top 10 securities movement for a specific index.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMoversTest() {
        String symbolId = null;
        String sort = null;
        Integer frequency = null;
        InlineResponse200 response = api.getMovers(symbolId, sort, frequency);

        // TODO: test validations
    }
}
