/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.api;

import com.kcjmowright.schwab.marketdata.model.CandleList;
import com.kcjmowright.schwab.marketdata.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PriceHistoryApi
 */
@Ignore
public class PriceHistoryApiTest {

    private final PriceHistoryApi api = new PriceHistoryApi();

    /**
     * Get PriceHistory for a single symbol and date ranges.
     *
     * Get historical Open, High, Low, Close, and Volume for a given frequency (i.e. aggregation).  Frequency available is dependent on periodType selected.  The datetime format is in EPOCH milliseconds.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPriceHistoryTest() {
        String symbol = null;
        String periodType = null;
        Integer period = null;
        String frequencyType = null;
        Integer frequency = null;
        Long startDate = null;
        Long endDate = null;
        Boolean needExtendedHoursData = null;
        Boolean needPreviousClose = null;
        CandleList response = api.getPriceHistory(symbol, periodType, period, frequencyType, frequency, startDate, endDate, needExtendedHoursData, needPreviousClose);

        // TODO: test validations
    }
}
