/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.api;

import com.kcjmowright.schwab.marketdata.model.ErrorResponse;
import com.kcjmowright.schwab.marketdata.model.QuoteResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QuotesApi
 */
@Ignore
public class QuotesApiTest {

    private final QuotesApi api = new QuotesApi();

    /**
     * Get Quote by single symbol.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getQuoteTest() {
        String symbolId = null;
        String fields = null;
        QuoteResponse response = api.getQuote(symbolId, fields);

        // TODO: test validations
    }
    /**
     * Get Quotes by list of symbols.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getQuotesTest() {
        String symbols = null;
        String fields = null;
        Boolean indicative = null;
        QuoteResponse response = api.getQuotes(symbols, fields, indicative);

        // TODO: test validations
    }
}
