/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.AssetMainType;
import com.kcjmowright.schwab.marketdata.model.EquityAssetSubType;
import com.kcjmowright.schwab.marketdata.model.ExtendedMarket;
import com.kcjmowright.schwab.marketdata.model.Fundamental;
import com.kcjmowright.schwab.marketdata.model.QuoteEquity;
import com.kcjmowright.schwab.marketdata.model.QuoteType;
import com.kcjmowright.schwab.marketdata.model.ReferenceEquity;
import com.kcjmowright.schwab.marketdata.model.RegularMarket;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Quote info of Equity security
 */
@Schema(description = "Quote info of Equity security")


public class EquityResponse implements QuoteResponseObject {
  @JsonProperty("assetMainType")
  private AssetMainType assetMainType = null;

  @JsonProperty("assetSubType")
  private EquityAssetSubType assetSubType = null;

  @JsonProperty("ssid")
  private Long ssid = null;

  @JsonProperty("symbol")
  private String symbol = null;

  @JsonProperty("realtime")
  private Boolean realtime = null;

  @JsonProperty("quoteType")
  private QuoteType quoteType = null;

  @JsonProperty("extended")
  private ExtendedMarket extended = null;

  @JsonProperty("fundamental")
  private Fundamental fundamental = null;

  @JsonProperty("quote")
  private QuoteEquity quote = null;

  @JsonProperty("reference")
  private ReferenceEquity reference = null;

  @JsonProperty("regular")
  private RegularMarket regular = null;

  public EquityResponse assetMainType(AssetMainType assetMainType) {
    this.assetMainType = assetMainType;
    return this;
  }

   /**
   * Get assetMainType
   * @return assetMainType
  **/
  @Schema(description = "")
  public AssetMainType getAssetMainType() {
    return assetMainType;
  }

  public void setAssetMainType(AssetMainType assetMainType) {
    this.assetMainType = assetMainType;
  }

  public EquityResponse assetSubType(EquityAssetSubType assetSubType) {
    this.assetSubType = assetSubType;
    return this;
  }

   /**
   * Get assetSubType
   * @return assetSubType
  **/
  @Schema(description = "")
  public EquityAssetSubType getAssetSubType() {
    return assetSubType;
  }

  public void setAssetSubType(EquityAssetSubType assetSubType) {
    this.assetSubType = assetSubType;
  }

  public EquityResponse ssid(Long ssid) {
    this.ssid = ssid;
    return this;
  }

   /**
   * SSID of instrument
   * @return ssid
  **/
  @Schema(example = "1234567890", description = "SSID of instrument")
  public Long getSsid() {
    return ssid;
  }

  public void setSsid(Long ssid) {
    this.ssid = ssid;
  }

  public EquityResponse symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol of instrument
   * @return symbol
  **/
  @Schema(example = "AAPL", description = "Symbol of instrument")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public EquityResponse realtime(Boolean realtime) {
    this.realtime = realtime;
    return this;
  }

   /**
   * is quote realtime
   * @return realtime
  **/
  @Schema(example = "true", description = "is quote realtime")
  public Boolean isRealtime() {
    return realtime;
  }

  public void setRealtime(Boolean realtime) {
    this.realtime = realtime;
  }

  public EquityResponse quoteType(QuoteType quoteType) {
    this.quoteType = quoteType;
    return this;
  }

   /**
   * Get quoteType
   * @return quoteType
  **/
  @Schema(description = "")
  public QuoteType getQuoteType() {
    return quoteType;
  }

  public void setQuoteType(QuoteType quoteType) {
    this.quoteType = quoteType;
  }

  public EquityResponse extended(ExtendedMarket extended) {
    this.extended = extended;
    return this;
  }

   /**
   * Get extended
   * @return extended
  **/
  @Schema(description = "")
  public ExtendedMarket getExtended() {
    return extended;
  }

  public void setExtended(ExtendedMarket extended) {
    this.extended = extended;
  }

  public EquityResponse fundamental(Fundamental fundamental) {
    this.fundamental = fundamental;
    return this;
  }

   /**
   * Get fundamental
   * @return fundamental
  **/
  @Schema(description = "")
  public Fundamental getFundamental() {
    return fundamental;
  }

  public void setFundamental(Fundamental fundamental) {
    this.fundamental = fundamental;
  }

  public EquityResponse quote(QuoteEquity quote) {
    this.quote = quote;
    return this;
  }

   /**
   * Get quote
   * @return quote
  **/
  @Schema(description = "")
  public QuoteEquity getQuote() {
    return quote;
  }

  public void setQuote(QuoteEquity quote) {
    this.quote = quote;
  }

  public EquityResponse reference(ReferenceEquity reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @Schema(description = "")
  public ReferenceEquity getReference() {
    return reference;
  }

  public void setReference(ReferenceEquity reference) {
    this.reference = reference;
  }

  public EquityResponse regular(RegularMarket regular) {
    this.regular = regular;
    return this;
  }

   /**
   * Get regular
   * @return regular
  **/
  @Schema(description = "")
  public RegularMarket getRegular() {
    return regular;
  }

  public void setRegular(RegularMarket regular) {
    this.regular = regular;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EquityResponse equityResponse = (EquityResponse) o;
    return Objects.equals(this.assetMainType, equityResponse.assetMainType) &&
        Objects.equals(this.assetSubType, equityResponse.assetSubType) &&
        Objects.equals(this.ssid, equityResponse.ssid) &&
        Objects.equals(this.symbol, equityResponse.symbol) &&
        Objects.equals(this.realtime, equityResponse.realtime) &&
        Objects.equals(this.quoteType, equityResponse.quoteType) &&
        Objects.equals(this.extended, equityResponse.extended) &&
        Objects.equals(this.fundamental, equityResponse.fundamental) &&
        Objects.equals(this.quote, equityResponse.quote) &&
        Objects.equals(this.reference, equityResponse.reference) &&
        Objects.equals(this.regular, equityResponse.regular);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetMainType, assetSubType, ssid, symbol, realtime, quoteType, extended, fundamental, quote, reference, regular);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EquityResponse {\n");
    
    sb.append("    assetMainType: ").append(toIndentedString(assetMainType)).append("\n");
    sb.append("    assetSubType: ").append(toIndentedString(assetSubType)).append("\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    realtime: ").append(toIndentedString(realtime)).append("\n");
    sb.append("    quoteType: ").append(toIndentedString(quoteType)).append("\n");
    sb.append("    extended: ").append(toIndentedString(extended)).append("\n");
    sb.append("    fundamental: ").append(toIndentedString(fundamental)).append("\n");
    sb.append("    quote: ").append(toIndentedString(quote)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    regular: ").append(toIndentedString(regular)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
