/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Who is responsible for triggering these errors.
 */
@Schema(description = "Who is responsible for triggering these errors.")


public class ErrorSource {
  @JsonProperty("pointer")
  private List<String> pointer = null;

  @JsonProperty("parameter")
  private String parameter = null;

  @JsonProperty("header")
  private String header = null;

   /**
   * list of attributes which lead to this error message.
   * @return pointer
  **/
  @Schema(example = "[\"/data/attributes/symbols\",\"/data/attributes/cusips\",\"/data/attributes/ssids\"]", description = "list of attributes which lead to this error message.")
  public List<String> getPointer() {
    return pointer;
  }

   /**
   * parameter name which lead to this error message.
   * @return parameter
  **/
  @Schema(example = "fields", description = "parameter name which lead to this error message.")
  public String getParameter() {
    return parameter;
  }

   /**
   * header name which lead to this error message.
   * @return header
  **/
  @Schema(example = "Schwab-Client-CorrelId", description = "header name which lead to this error message.")
  public String getHeader() {
    return header;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorSource errorSource = (ErrorSource) o;
    return Objects.equals(this.pointer, errorSource.pointer) &&
        Objects.equals(this.parameter, errorSource.parameter) &&
        Objects.equals(this.header, errorSource.header);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointer, parameter, header);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorSource {\n");
    
    sb.append("    pointer: ").append(toIndentedString(pointer)).append("\n");
    sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
