/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.Expiration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ExpirationChain
 */



public class ExpirationChain {
  @JsonProperty("status")
  private String status = null;

  @JsonProperty("expirationList")
  private List<Expiration> expirationList = null;

  public ExpirationChain status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ExpirationChain expirationList(List<Expiration> expirationList) {
    this.expirationList = expirationList;
    return this;
  }

  public ExpirationChain addExpirationListItem(Expiration expirationListItem) {
    if (this.expirationList == null) {
      this.expirationList = new ArrayList<>();
    }
    this.expirationList.add(expirationListItem);
    return this;
  }

   /**
   * Get expirationList
   * @return expirationList
  **/
  @Schema(description = "")
  public List<Expiration> getExpirationList() {
    return expirationList;
  }

  public void setExpirationList(List<Expiration> expirationList) {
    this.expirationList = expirationList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpirationChain expirationChain = (ExpirationChain) o;
    return Objects.equals(this.status, expirationChain.status) &&
        Objects.equals(this.expirationList, expirationChain.expirationList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, expirationList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpirationChain {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    expirationList: ").append(toIndentedString(expirationList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
