/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.ExpirationType;
import com.kcjmowright.schwab.marketdata.model.SettlementType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * expiration type
 */
@Schema(description = "expiration type")


public class Expiration {
  @JsonProperty("daysToExpiration")
  private Integer daysToExpiration = null;

  @JsonProperty("expiration")
  private String expiration = null;

  @JsonProperty("expirationType")
  private ExpirationType expirationType = null;

  @JsonProperty("standard")
  private Boolean standard = null;

  @JsonProperty("settlementType")
  private SettlementType settlementType = null;

  @JsonProperty("optionRoots")
  private String optionRoots = null;

  public Expiration daysToExpiration(Integer daysToExpiration) {
    this.daysToExpiration = daysToExpiration;
    return this;
  }

   /**
   * Get daysToExpiration
   * @return daysToExpiration
  **/
  @Schema(description = "")
  public Integer getDaysToExpiration() {
    return daysToExpiration;
  }

  public void setDaysToExpiration(Integer daysToExpiration) {
    this.daysToExpiration = daysToExpiration;
  }

  public Expiration expiration(String expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @Schema(description = "")
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }

  public Expiration expirationType(ExpirationType expirationType) {
    this.expirationType = expirationType;
    return this;
  }

   /**
   * Get expirationType
   * @return expirationType
  **/
  @Schema(description = "")
  public ExpirationType getExpirationType() {
    return expirationType;
  }

  public void setExpirationType(ExpirationType expirationType) {
    this.expirationType = expirationType;
  }

  public Expiration standard(Boolean standard) {
    this.standard = standard;
    return this;
  }

   /**
   * Get standard
   * @return standard
  **/
  @Schema(description = "")
  public Boolean isStandard() {
    return standard;
  }

  public void setStandard(Boolean standard) {
    this.standard = standard;
  }

  public Expiration settlementType(SettlementType settlementType) {
    this.settlementType = settlementType;
    return this;
  }

   /**
   * Get settlementType
   * @return settlementType
  **/
  @Schema(description = "")
  public SettlementType getSettlementType() {
    return settlementType;
  }

  public void setSettlementType(SettlementType settlementType) {
    this.settlementType = settlementType;
  }

  public Expiration optionRoots(String optionRoots) {
    this.optionRoots = optionRoots;
    return this;
  }

   /**
   * Get optionRoots
   * @return optionRoots
  **/
  @Schema(description = "")
  public String getOptionRoots() {
    return optionRoots;
  }

  public void setOptionRoots(String optionRoots) {
    this.optionRoots = optionRoots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Expiration expiration = (Expiration) o;
    return Objects.equals(this.daysToExpiration, expiration.daysToExpiration) &&
        Objects.equals(this.expiration, expiration.expiration) &&
        Objects.equals(this.expirationType, expiration.expirationType) &&
        Objects.equals(this.standard, expiration.standard) &&
        Objects.equals(this.settlementType, expiration.settlementType) &&
        Objects.equals(this.optionRoots, expiration.optionRoots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daysToExpiration, expiration, expirationType, standard, settlementType, optionRoots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Expiration {\n");
    
    sb.append("    daysToExpiration: ").append(toIndentedString(daysToExpiration)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    expirationType: ").append(toIndentedString(expirationType)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("    settlementType: ").append(toIndentedString(settlementType)).append("\n");
    sb.append("    optionRoots: ").append(toIndentedString(optionRoots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
