/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * FundamentalInst
 */



public class FundamentalInst {
  @JsonProperty("symbol")
  private String symbol = null;

  @JsonProperty("high52")
  private Double high52 = null;

  @JsonProperty("low52")
  private Double low52 = null;

  @JsonProperty("dividendAmount")
  private Double dividendAmount = null;

  @JsonProperty("dividendYield")
  private Double dividendYield = null;

  @JsonProperty("dividendDate")
  private String dividendDate = null;

  @JsonProperty("peRatio")
  private Double peRatio = null;

  @JsonProperty("pegRatio")
  private Double pegRatio = null;

  @JsonProperty("pbRatio")
  private Double pbRatio = null;

  @JsonProperty("prRatio")
  private Double prRatio = null;

  @JsonProperty("pcfRatio")
  private Double pcfRatio = null;

  @JsonProperty("grossMarginTTM")
  private Double grossMarginTTM = null;

  @JsonProperty("grossMarginMRQ")
  private Double grossMarginMRQ = null;

  @JsonProperty("netProfitMarginTTM")
  private Double netProfitMarginTTM = null;

  @JsonProperty("netProfitMarginMRQ")
  private Double netProfitMarginMRQ = null;

  @JsonProperty("operatingMarginTTM")
  private Double operatingMarginTTM = null;

  @JsonProperty("operatingMarginMRQ")
  private Double operatingMarginMRQ = null;

  @JsonProperty("returnOnEquity")
  private Double returnOnEquity = null;

  @JsonProperty("returnOnAssets")
  private Double returnOnAssets = null;

  @JsonProperty("returnOnInvestment")
  private Double returnOnInvestment = null;

  @JsonProperty("quickRatio")
  private Double quickRatio = null;

  @JsonProperty("currentRatio")
  private Double currentRatio = null;

  @JsonProperty("interestCoverage")
  private Double interestCoverage = null;

  @JsonProperty("totalDebtToCapital")
  private Double totalDebtToCapital = null;

  @JsonProperty("ltDebtToEquity")
  private Double ltDebtToEquity = null;

  @JsonProperty("totalDebtToEquity")
  private Double totalDebtToEquity = null;

  @JsonProperty("epsTTM")
  private Double epsTTM = null;

  @JsonProperty("epsChangePercentTTM")
  private Double epsChangePercentTTM = null;

  @JsonProperty("epsChangeYear")
  private Double epsChangeYear = null;

  @JsonProperty("epsChange")
  private Double epsChange = null;

  @JsonProperty("revChangeYear")
  private Double revChangeYear = null;

  @JsonProperty("revChangeTTM")
  private Double revChangeTTM = null;

  @JsonProperty("revChangeIn")
  private Double revChangeIn = null;

  @JsonProperty("sharesOutstanding")
  private Double sharesOutstanding = null;

  @JsonProperty("marketCapFloat")
  private Double marketCapFloat = null;

  @JsonProperty("marketCap")
  private Double marketCap = null;

  @JsonProperty("bookValuePerShare")
  private Double bookValuePerShare = null;

  @JsonProperty("shortIntToFloat")
  private Double shortIntToFloat = null;

  @JsonProperty("shortIntDayToCover")
  private Double shortIntDayToCover = null;

  @JsonProperty("divGrowthRate3Year")
  private Double divGrowthRate3Year = null;

  @JsonProperty("dividendPayAmount")
  private Double dividendPayAmount = null;

  @JsonProperty("dividendPayDate")
  private String dividendPayDate = null;

  @JsonProperty("beta")
  private Double beta = null;

  @JsonProperty("vol1DayAvg")
  private Double vol1DayAvg = null;

  @JsonProperty("vol10DayAvg")
  private Double vol10DayAvg = null;

  @JsonProperty("vol3MonthAvg")
  private Double vol3MonthAvg = null;

  @JsonProperty("avg10DaysVolume")
  private Long avg10DaysVolume = null;

  @JsonProperty("avg1DayVolume")
  private Long avg1DayVolume = null;

  @JsonProperty("avg3MonthVolume")
  private Long avg3MonthVolume = null;

  @JsonProperty("declarationDate")
  private String declarationDate = null;

  @JsonProperty("dividendFreq")
  private Integer dividendFreq = null;

  @JsonProperty("eps")
  private Double eps = null;

  @JsonProperty("corpactionDate")
  private String corpactionDate = null;

  @JsonProperty("dtnVolume")
  private Long dtnVolume = null;

  @JsonProperty("nextDividendPayDate")
  private String nextDividendPayDate = null;

  @JsonProperty("nextDividendDate")
  private String nextDividendDate = null;

  @JsonProperty("fundLeverageFactor")
  private Double fundLeverageFactor = null;

  @JsonProperty("fundStrategy")
  private String fundStrategy = null;

  public FundamentalInst symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public FundamentalInst high52(Double high52) {
    this.high52 = high52;
    return this;
  }

   /**
   * Get high52
   * @return high52
  **/
  @Schema(description = "")
  public Double getHigh52() {
    return high52;
  }

  public void setHigh52(Double high52) {
    this.high52 = high52;
  }

  public FundamentalInst low52(Double low52) {
    this.low52 = low52;
    return this;
  }

   /**
   * Get low52
   * @return low52
  **/
  @Schema(description = "")
  public Double getLow52() {
    return low52;
  }

  public void setLow52(Double low52) {
    this.low52 = low52;
  }

  public FundamentalInst dividendAmount(Double dividendAmount) {
    this.dividendAmount = dividendAmount;
    return this;
  }

   /**
   * Get dividendAmount
   * @return dividendAmount
  **/
  @Schema(description = "")
  public Double getDividendAmount() {
    return dividendAmount;
  }

  public void setDividendAmount(Double dividendAmount) {
    this.dividendAmount = dividendAmount;
  }

  public FundamentalInst dividendYield(Double dividendYield) {
    this.dividendYield = dividendYield;
    return this;
  }

   /**
   * Get dividendYield
   * @return dividendYield
  **/
  @Schema(description = "")
  public Double getDividendYield() {
    return dividendYield;
  }

  public void setDividendYield(Double dividendYield) {
    this.dividendYield = dividendYield;
  }

  public FundamentalInst dividendDate(String dividendDate) {
    this.dividendDate = dividendDate;
    return this;
  }

   /**
   * Get dividendDate
   * @return dividendDate
  **/
  @Schema(description = "")
  public String getDividendDate() {
    return dividendDate;
  }

  public void setDividendDate(String dividendDate) {
    this.dividendDate = dividendDate;
  }

  public FundamentalInst peRatio(Double peRatio) {
    this.peRatio = peRatio;
    return this;
  }

   /**
   * Get peRatio
   * @return peRatio
  **/
  @Schema(description = "")
  public Double getPeRatio() {
    return peRatio;
  }

  public void setPeRatio(Double peRatio) {
    this.peRatio = peRatio;
  }

  public FundamentalInst pegRatio(Double pegRatio) {
    this.pegRatio = pegRatio;
    return this;
  }

   /**
   * Get pegRatio
   * @return pegRatio
  **/
  @Schema(description = "")
  public Double getPegRatio() {
    return pegRatio;
  }

  public void setPegRatio(Double pegRatio) {
    this.pegRatio = pegRatio;
  }

  public FundamentalInst pbRatio(Double pbRatio) {
    this.pbRatio = pbRatio;
    return this;
  }

   /**
   * Get pbRatio
   * @return pbRatio
  **/
  @Schema(description = "")
  public Double getPbRatio() {
    return pbRatio;
  }

  public void setPbRatio(Double pbRatio) {
    this.pbRatio = pbRatio;
  }

  public FundamentalInst prRatio(Double prRatio) {
    this.prRatio = prRatio;
    return this;
  }

   /**
   * Get prRatio
   * @return prRatio
  **/
  @Schema(description = "")
  public Double getPrRatio() {
    return prRatio;
  }

  public void setPrRatio(Double prRatio) {
    this.prRatio = prRatio;
  }

  public FundamentalInst pcfRatio(Double pcfRatio) {
    this.pcfRatio = pcfRatio;
    return this;
  }

   /**
   * Get pcfRatio
   * @return pcfRatio
  **/
  @Schema(description = "")
  public Double getPcfRatio() {
    return pcfRatio;
  }

  public void setPcfRatio(Double pcfRatio) {
    this.pcfRatio = pcfRatio;
  }

  public FundamentalInst grossMarginTTM(Double grossMarginTTM) {
    this.grossMarginTTM = grossMarginTTM;
    return this;
  }

   /**
   * Get grossMarginTTM
   * @return grossMarginTTM
  **/
  @Schema(description = "")
  public Double getGrossMarginTTM() {
    return grossMarginTTM;
  }

  public void setGrossMarginTTM(Double grossMarginTTM) {
    this.grossMarginTTM = grossMarginTTM;
  }

  public FundamentalInst grossMarginMRQ(Double grossMarginMRQ) {
    this.grossMarginMRQ = grossMarginMRQ;
    return this;
  }

   /**
   * Get grossMarginMRQ
   * @return grossMarginMRQ
  **/
  @Schema(description = "")
  public Double getGrossMarginMRQ() {
    return grossMarginMRQ;
  }

  public void setGrossMarginMRQ(Double grossMarginMRQ) {
    this.grossMarginMRQ = grossMarginMRQ;
  }

  public FundamentalInst netProfitMarginTTM(Double netProfitMarginTTM) {
    this.netProfitMarginTTM = netProfitMarginTTM;
    return this;
  }

   /**
   * Get netProfitMarginTTM
   * @return netProfitMarginTTM
  **/
  @Schema(description = "")
  public Double getNetProfitMarginTTM() {
    return netProfitMarginTTM;
  }

  public void setNetProfitMarginTTM(Double netProfitMarginTTM) {
    this.netProfitMarginTTM = netProfitMarginTTM;
  }

  public FundamentalInst netProfitMarginMRQ(Double netProfitMarginMRQ) {
    this.netProfitMarginMRQ = netProfitMarginMRQ;
    return this;
  }

   /**
   * Get netProfitMarginMRQ
   * @return netProfitMarginMRQ
  **/
  @Schema(description = "")
  public Double getNetProfitMarginMRQ() {
    return netProfitMarginMRQ;
  }

  public void setNetProfitMarginMRQ(Double netProfitMarginMRQ) {
    this.netProfitMarginMRQ = netProfitMarginMRQ;
  }

  public FundamentalInst operatingMarginTTM(Double operatingMarginTTM) {
    this.operatingMarginTTM = operatingMarginTTM;
    return this;
  }

   /**
   * Get operatingMarginTTM
   * @return operatingMarginTTM
  **/
  @Schema(description = "")
  public Double getOperatingMarginTTM() {
    return operatingMarginTTM;
  }

  public void setOperatingMarginTTM(Double operatingMarginTTM) {
    this.operatingMarginTTM = operatingMarginTTM;
  }

  public FundamentalInst operatingMarginMRQ(Double operatingMarginMRQ) {
    this.operatingMarginMRQ = operatingMarginMRQ;
    return this;
  }

   /**
   * Get operatingMarginMRQ
   * @return operatingMarginMRQ
  **/
  @Schema(description = "")
  public Double getOperatingMarginMRQ() {
    return operatingMarginMRQ;
  }

  public void setOperatingMarginMRQ(Double operatingMarginMRQ) {
    this.operatingMarginMRQ = operatingMarginMRQ;
  }

  public FundamentalInst returnOnEquity(Double returnOnEquity) {
    this.returnOnEquity = returnOnEquity;
    return this;
  }

   /**
   * Get returnOnEquity
   * @return returnOnEquity
  **/
  @Schema(description = "")
  public Double getReturnOnEquity() {
    return returnOnEquity;
  }

  public void setReturnOnEquity(Double returnOnEquity) {
    this.returnOnEquity = returnOnEquity;
  }

  public FundamentalInst returnOnAssets(Double returnOnAssets) {
    this.returnOnAssets = returnOnAssets;
    return this;
  }

   /**
   * Get returnOnAssets
   * @return returnOnAssets
  **/
  @Schema(description = "")
  public Double getReturnOnAssets() {
    return returnOnAssets;
  }

  public void setReturnOnAssets(Double returnOnAssets) {
    this.returnOnAssets = returnOnAssets;
  }

  public FundamentalInst returnOnInvestment(Double returnOnInvestment) {
    this.returnOnInvestment = returnOnInvestment;
    return this;
  }

   /**
   * Get returnOnInvestment
   * @return returnOnInvestment
  **/
  @Schema(description = "")
  public Double getReturnOnInvestment() {
    return returnOnInvestment;
  }

  public void setReturnOnInvestment(Double returnOnInvestment) {
    this.returnOnInvestment = returnOnInvestment;
  }

  public FundamentalInst quickRatio(Double quickRatio) {
    this.quickRatio = quickRatio;
    return this;
  }

   /**
   * Get quickRatio
   * @return quickRatio
  **/
  @Schema(description = "")
  public Double getQuickRatio() {
    return quickRatio;
  }

  public void setQuickRatio(Double quickRatio) {
    this.quickRatio = quickRatio;
  }

  public FundamentalInst currentRatio(Double currentRatio) {
    this.currentRatio = currentRatio;
    return this;
  }

   /**
   * Get currentRatio
   * @return currentRatio
  **/
  @Schema(description = "")
  public Double getCurrentRatio() {
    return currentRatio;
  }

  public void setCurrentRatio(Double currentRatio) {
    this.currentRatio = currentRatio;
  }

  public FundamentalInst interestCoverage(Double interestCoverage) {
    this.interestCoverage = interestCoverage;
    return this;
  }

   /**
   * Get interestCoverage
   * @return interestCoverage
  **/
  @Schema(description = "")
  public Double getInterestCoverage() {
    return interestCoverage;
  }

  public void setInterestCoverage(Double interestCoverage) {
    this.interestCoverage = interestCoverage;
  }

  public FundamentalInst totalDebtToCapital(Double totalDebtToCapital) {
    this.totalDebtToCapital = totalDebtToCapital;
    return this;
  }

   /**
   * Get totalDebtToCapital
   * @return totalDebtToCapital
  **/
  @Schema(description = "")
  public Double getTotalDebtToCapital() {
    return totalDebtToCapital;
  }

  public void setTotalDebtToCapital(Double totalDebtToCapital) {
    this.totalDebtToCapital = totalDebtToCapital;
  }

  public FundamentalInst ltDebtToEquity(Double ltDebtToEquity) {
    this.ltDebtToEquity = ltDebtToEquity;
    return this;
  }

   /**
   * Get ltDebtToEquity
   * @return ltDebtToEquity
  **/
  @Schema(description = "")
  public Double getLtDebtToEquity() {
    return ltDebtToEquity;
  }

  public void setLtDebtToEquity(Double ltDebtToEquity) {
    this.ltDebtToEquity = ltDebtToEquity;
  }

  public FundamentalInst totalDebtToEquity(Double totalDebtToEquity) {
    this.totalDebtToEquity = totalDebtToEquity;
    return this;
  }

   /**
   * Get totalDebtToEquity
   * @return totalDebtToEquity
  **/
  @Schema(description = "")
  public Double getTotalDebtToEquity() {
    return totalDebtToEquity;
  }

  public void setTotalDebtToEquity(Double totalDebtToEquity) {
    this.totalDebtToEquity = totalDebtToEquity;
  }

  public FundamentalInst epsTTM(Double epsTTM) {
    this.epsTTM = epsTTM;
    return this;
  }

   /**
   * Get epsTTM
   * @return epsTTM
  **/
  @Schema(description = "")
  public Double getEpsTTM() {
    return epsTTM;
  }

  public void setEpsTTM(Double epsTTM) {
    this.epsTTM = epsTTM;
  }

  public FundamentalInst epsChangePercentTTM(Double epsChangePercentTTM) {
    this.epsChangePercentTTM = epsChangePercentTTM;
    return this;
  }

   /**
   * Get epsChangePercentTTM
   * @return epsChangePercentTTM
  **/
  @Schema(description = "")
  public Double getEpsChangePercentTTM() {
    return epsChangePercentTTM;
  }

  public void setEpsChangePercentTTM(Double epsChangePercentTTM) {
    this.epsChangePercentTTM = epsChangePercentTTM;
  }

  public FundamentalInst epsChangeYear(Double epsChangeYear) {
    this.epsChangeYear = epsChangeYear;
    return this;
  }

   /**
   * Get epsChangeYear
   * @return epsChangeYear
  **/
  @Schema(description = "")
  public Double getEpsChangeYear() {
    return epsChangeYear;
  }

  public void setEpsChangeYear(Double epsChangeYear) {
    this.epsChangeYear = epsChangeYear;
  }

  public FundamentalInst epsChange(Double epsChange) {
    this.epsChange = epsChange;
    return this;
  }

   /**
   * Get epsChange
   * @return epsChange
  **/
  @Schema(description = "")
  public Double getEpsChange() {
    return epsChange;
  }

  public void setEpsChange(Double epsChange) {
    this.epsChange = epsChange;
  }

  public FundamentalInst revChangeYear(Double revChangeYear) {
    this.revChangeYear = revChangeYear;
    return this;
  }

   /**
   * Get revChangeYear
   * @return revChangeYear
  **/
  @Schema(description = "")
  public Double getRevChangeYear() {
    return revChangeYear;
  }

  public void setRevChangeYear(Double revChangeYear) {
    this.revChangeYear = revChangeYear;
  }

  public FundamentalInst revChangeTTM(Double revChangeTTM) {
    this.revChangeTTM = revChangeTTM;
    return this;
  }

   /**
   * Get revChangeTTM
   * @return revChangeTTM
  **/
  @Schema(description = "")
  public Double getRevChangeTTM() {
    return revChangeTTM;
  }

  public void setRevChangeTTM(Double revChangeTTM) {
    this.revChangeTTM = revChangeTTM;
  }

  public FundamentalInst revChangeIn(Double revChangeIn) {
    this.revChangeIn = revChangeIn;
    return this;
  }

   /**
   * Get revChangeIn
   * @return revChangeIn
  **/
  @Schema(description = "")
  public Double getRevChangeIn() {
    return revChangeIn;
  }

  public void setRevChangeIn(Double revChangeIn) {
    this.revChangeIn = revChangeIn;
  }

  public FundamentalInst sharesOutstanding(Double sharesOutstanding) {
    this.sharesOutstanding = sharesOutstanding;
    return this;
  }

   /**
   * Get sharesOutstanding
   * @return sharesOutstanding
  **/
  @Schema(description = "")
  public Double getSharesOutstanding() {
    return sharesOutstanding;
  }

  public void setSharesOutstanding(Double sharesOutstanding) {
    this.sharesOutstanding = sharesOutstanding;
  }

  public FundamentalInst marketCapFloat(Double marketCapFloat) {
    this.marketCapFloat = marketCapFloat;
    return this;
  }

   /**
   * Get marketCapFloat
   * @return marketCapFloat
  **/
  @Schema(description = "")
  public Double getMarketCapFloat() {
    return marketCapFloat;
  }

  public void setMarketCapFloat(Double marketCapFloat) {
    this.marketCapFloat = marketCapFloat;
  }

  public FundamentalInst marketCap(Double marketCap) {
    this.marketCap = marketCap;
    return this;
  }

   /**
   * Get marketCap
   * @return marketCap
  **/
  @Schema(description = "")
  public Double getMarketCap() {
    return marketCap;
  }

  public void setMarketCap(Double marketCap) {
    this.marketCap = marketCap;
  }

  public FundamentalInst bookValuePerShare(Double bookValuePerShare) {
    this.bookValuePerShare = bookValuePerShare;
    return this;
  }

   /**
   * Get bookValuePerShare
   * @return bookValuePerShare
  **/
  @Schema(description = "")
  public Double getBookValuePerShare() {
    return bookValuePerShare;
  }

  public void setBookValuePerShare(Double bookValuePerShare) {
    this.bookValuePerShare = bookValuePerShare;
  }

  public FundamentalInst shortIntToFloat(Double shortIntToFloat) {
    this.shortIntToFloat = shortIntToFloat;
    return this;
  }

   /**
   * Get shortIntToFloat
   * @return shortIntToFloat
  **/
  @Schema(description = "")
  public Double getShortIntToFloat() {
    return shortIntToFloat;
  }

  public void setShortIntToFloat(Double shortIntToFloat) {
    this.shortIntToFloat = shortIntToFloat;
  }

  public FundamentalInst shortIntDayToCover(Double shortIntDayToCover) {
    this.shortIntDayToCover = shortIntDayToCover;
    return this;
  }

   /**
   * Get shortIntDayToCover
   * @return shortIntDayToCover
  **/
  @Schema(description = "")
  public Double getShortIntDayToCover() {
    return shortIntDayToCover;
  }

  public void setShortIntDayToCover(Double shortIntDayToCover) {
    this.shortIntDayToCover = shortIntDayToCover;
  }

  public FundamentalInst divGrowthRate3Year(Double divGrowthRate3Year) {
    this.divGrowthRate3Year = divGrowthRate3Year;
    return this;
  }

   /**
   * Get divGrowthRate3Year
   * @return divGrowthRate3Year
  **/
  @Schema(description = "")
  public Double getDivGrowthRate3Year() {
    return divGrowthRate3Year;
  }

  public void setDivGrowthRate3Year(Double divGrowthRate3Year) {
    this.divGrowthRate3Year = divGrowthRate3Year;
  }

  public FundamentalInst dividendPayAmount(Double dividendPayAmount) {
    this.dividendPayAmount = dividendPayAmount;
    return this;
  }

   /**
   * Get dividendPayAmount
   * @return dividendPayAmount
  **/
  @Schema(description = "")
  public Double getDividendPayAmount() {
    return dividendPayAmount;
  }

  public void setDividendPayAmount(Double dividendPayAmount) {
    this.dividendPayAmount = dividendPayAmount;
  }

  public FundamentalInst dividendPayDate(String dividendPayDate) {
    this.dividendPayDate = dividendPayDate;
    return this;
  }

   /**
   * Get dividendPayDate
   * @return dividendPayDate
  **/
  @Schema(description = "")
  public String getDividendPayDate() {
    return dividendPayDate;
  }

  public void setDividendPayDate(String dividendPayDate) {
    this.dividendPayDate = dividendPayDate;
  }

  public FundamentalInst beta(Double beta) {
    this.beta = beta;
    return this;
  }

   /**
   * Get beta
   * @return beta
  **/
  @Schema(description = "")
  public Double getBeta() {
    return beta;
  }

  public void setBeta(Double beta) {
    this.beta = beta;
  }

  public FundamentalInst vol1DayAvg(Double vol1DayAvg) {
    this.vol1DayAvg = vol1DayAvg;
    return this;
  }

   /**
   * Get vol1DayAvg
   * @return vol1DayAvg
  **/
  @Schema(description = "")
  public Double getVol1DayAvg() {
    return vol1DayAvg;
  }

  public void setVol1DayAvg(Double vol1DayAvg) {
    this.vol1DayAvg = vol1DayAvg;
  }

  public FundamentalInst vol10DayAvg(Double vol10DayAvg) {
    this.vol10DayAvg = vol10DayAvg;
    return this;
  }

   /**
   * Get vol10DayAvg
   * @return vol10DayAvg
  **/
  @Schema(description = "")
  public Double getVol10DayAvg() {
    return vol10DayAvg;
  }

  public void setVol10DayAvg(Double vol10DayAvg) {
    this.vol10DayAvg = vol10DayAvg;
  }

  public FundamentalInst vol3MonthAvg(Double vol3MonthAvg) {
    this.vol3MonthAvg = vol3MonthAvg;
    return this;
  }

   /**
   * Get vol3MonthAvg
   * @return vol3MonthAvg
  **/
  @Schema(description = "")
  public Double getVol3MonthAvg() {
    return vol3MonthAvg;
  }

  public void setVol3MonthAvg(Double vol3MonthAvg) {
    this.vol3MonthAvg = vol3MonthAvg;
  }

  public FundamentalInst avg10DaysVolume(Long avg10DaysVolume) {
    this.avg10DaysVolume = avg10DaysVolume;
    return this;
  }

   /**
   * Get avg10DaysVolume
   * @return avg10DaysVolume
  **/
  @Schema(description = "")
  public Long getAvg10DaysVolume() {
    return avg10DaysVolume;
  }

  public void setAvg10DaysVolume(Long avg10DaysVolume) {
    this.avg10DaysVolume = avg10DaysVolume;
  }

  public FundamentalInst avg1DayVolume(Long avg1DayVolume) {
    this.avg1DayVolume = avg1DayVolume;
    return this;
  }

   /**
   * Get avg1DayVolume
   * @return avg1DayVolume
  **/
  @Schema(description = "")
  public Long getAvg1DayVolume() {
    return avg1DayVolume;
  }

  public void setAvg1DayVolume(Long avg1DayVolume) {
    this.avg1DayVolume = avg1DayVolume;
  }

  public FundamentalInst avg3MonthVolume(Long avg3MonthVolume) {
    this.avg3MonthVolume = avg3MonthVolume;
    return this;
  }

   /**
   * Get avg3MonthVolume
   * @return avg3MonthVolume
  **/
  @Schema(description = "")
  public Long getAvg3MonthVolume() {
    return avg3MonthVolume;
  }

  public void setAvg3MonthVolume(Long avg3MonthVolume) {
    this.avg3MonthVolume = avg3MonthVolume;
  }

  public FundamentalInst declarationDate(String declarationDate) {
    this.declarationDate = declarationDate;
    return this;
  }

   /**
   * Get declarationDate
   * @return declarationDate
  **/
  @Schema(description = "")
  public String getDeclarationDate() {
    return declarationDate;
  }

  public void setDeclarationDate(String declarationDate) {
    this.declarationDate = declarationDate;
  }

  public FundamentalInst dividendFreq(Integer dividendFreq) {
    this.dividendFreq = dividendFreq;
    return this;
  }

   /**
   * Get dividendFreq
   * @return dividendFreq
  **/
  @Schema(description = "")
  public Integer getDividendFreq() {
    return dividendFreq;
  }

  public void setDividendFreq(Integer dividendFreq) {
    this.dividendFreq = dividendFreq;
  }

  public FundamentalInst eps(Double eps) {
    this.eps = eps;
    return this;
  }

   /**
   * Get eps
   * @return eps
  **/
  @Schema(description = "")
  public Double getEps() {
    return eps;
  }

  public void setEps(Double eps) {
    this.eps = eps;
  }

  public FundamentalInst corpactionDate(String corpactionDate) {
    this.corpactionDate = corpactionDate;
    return this;
  }

   /**
   * Get corpactionDate
   * @return corpactionDate
  **/
  @Schema(description = "")
  public String getCorpactionDate() {
    return corpactionDate;
  }

  public void setCorpactionDate(String corpactionDate) {
    this.corpactionDate = corpactionDate;
  }

  public FundamentalInst dtnVolume(Long dtnVolume) {
    this.dtnVolume = dtnVolume;
    return this;
  }

   /**
   * Get dtnVolume
   * @return dtnVolume
  **/
  @Schema(description = "")
  public Long getDtnVolume() {
    return dtnVolume;
  }

  public void setDtnVolume(Long dtnVolume) {
    this.dtnVolume = dtnVolume;
  }

  public FundamentalInst nextDividendPayDate(String nextDividendPayDate) {
    this.nextDividendPayDate = nextDividendPayDate;
    return this;
  }

   /**
   * Get nextDividendPayDate
   * @return nextDividendPayDate
  **/
  @Schema(description = "")
  public String getNextDividendPayDate() {
    return nextDividendPayDate;
  }

  public void setNextDividendPayDate(String nextDividendPayDate) {
    this.nextDividendPayDate = nextDividendPayDate;
  }

  public FundamentalInst nextDividendDate(String nextDividendDate) {
    this.nextDividendDate = nextDividendDate;
    return this;
  }

   /**
   * Get nextDividendDate
   * @return nextDividendDate
  **/
  @Schema(description = "")
  public String getNextDividendDate() {
    return nextDividendDate;
  }

  public void setNextDividendDate(String nextDividendDate) {
    this.nextDividendDate = nextDividendDate;
  }

  public FundamentalInst fundLeverageFactor(Double fundLeverageFactor) {
    this.fundLeverageFactor = fundLeverageFactor;
    return this;
  }

   /**
   * Get fundLeverageFactor
   * @return fundLeverageFactor
  **/
  @Schema(description = "")
  public Double getFundLeverageFactor() {
    return fundLeverageFactor;
  }

  public void setFundLeverageFactor(Double fundLeverageFactor) {
    this.fundLeverageFactor = fundLeverageFactor;
  }

  public FundamentalInst fundStrategy(String fundStrategy) {
    this.fundStrategy = fundStrategy;
    return this;
  }

   /**
   * Get fundStrategy
   * @return fundStrategy
  **/
  @Schema(description = "")
  public String getFundStrategy() {
    return fundStrategy;
  }

  public void setFundStrategy(String fundStrategy) {
    this.fundStrategy = fundStrategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundamentalInst fundamentalInst = (FundamentalInst) o;
    return Objects.equals(this.symbol, fundamentalInst.symbol) &&
        Objects.equals(this.high52, fundamentalInst.high52) &&
        Objects.equals(this.low52, fundamentalInst.low52) &&
        Objects.equals(this.dividendAmount, fundamentalInst.dividendAmount) &&
        Objects.equals(this.dividendYield, fundamentalInst.dividendYield) &&
        Objects.equals(this.dividendDate, fundamentalInst.dividendDate) &&
        Objects.equals(this.peRatio, fundamentalInst.peRatio) &&
        Objects.equals(this.pegRatio, fundamentalInst.pegRatio) &&
        Objects.equals(this.pbRatio, fundamentalInst.pbRatio) &&
        Objects.equals(this.prRatio, fundamentalInst.prRatio) &&
        Objects.equals(this.pcfRatio, fundamentalInst.pcfRatio) &&
        Objects.equals(this.grossMarginTTM, fundamentalInst.grossMarginTTM) &&
        Objects.equals(this.grossMarginMRQ, fundamentalInst.grossMarginMRQ) &&
        Objects.equals(this.netProfitMarginTTM, fundamentalInst.netProfitMarginTTM) &&
        Objects.equals(this.netProfitMarginMRQ, fundamentalInst.netProfitMarginMRQ) &&
        Objects.equals(this.operatingMarginTTM, fundamentalInst.operatingMarginTTM) &&
        Objects.equals(this.operatingMarginMRQ, fundamentalInst.operatingMarginMRQ) &&
        Objects.equals(this.returnOnEquity, fundamentalInst.returnOnEquity) &&
        Objects.equals(this.returnOnAssets, fundamentalInst.returnOnAssets) &&
        Objects.equals(this.returnOnInvestment, fundamentalInst.returnOnInvestment) &&
        Objects.equals(this.quickRatio, fundamentalInst.quickRatio) &&
        Objects.equals(this.currentRatio, fundamentalInst.currentRatio) &&
        Objects.equals(this.interestCoverage, fundamentalInst.interestCoverage) &&
        Objects.equals(this.totalDebtToCapital, fundamentalInst.totalDebtToCapital) &&
        Objects.equals(this.ltDebtToEquity, fundamentalInst.ltDebtToEquity) &&
        Objects.equals(this.totalDebtToEquity, fundamentalInst.totalDebtToEquity) &&
        Objects.equals(this.epsTTM, fundamentalInst.epsTTM) &&
        Objects.equals(this.epsChangePercentTTM, fundamentalInst.epsChangePercentTTM) &&
        Objects.equals(this.epsChangeYear, fundamentalInst.epsChangeYear) &&
        Objects.equals(this.epsChange, fundamentalInst.epsChange) &&
        Objects.equals(this.revChangeYear, fundamentalInst.revChangeYear) &&
        Objects.equals(this.revChangeTTM, fundamentalInst.revChangeTTM) &&
        Objects.equals(this.revChangeIn, fundamentalInst.revChangeIn) &&
        Objects.equals(this.sharesOutstanding, fundamentalInst.sharesOutstanding) &&
        Objects.equals(this.marketCapFloat, fundamentalInst.marketCapFloat) &&
        Objects.equals(this.marketCap, fundamentalInst.marketCap) &&
        Objects.equals(this.bookValuePerShare, fundamentalInst.bookValuePerShare) &&
        Objects.equals(this.shortIntToFloat, fundamentalInst.shortIntToFloat) &&
        Objects.equals(this.shortIntDayToCover, fundamentalInst.shortIntDayToCover) &&
        Objects.equals(this.divGrowthRate3Year, fundamentalInst.divGrowthRate3Year) &&
        Objects.equals(this.dividendPayAmount, fundamentalInst.dividendPayAmount) &&
        Objects.equals(this.dividendPayDate, fundamentalInst.dividendPayDate) &&
        Objects.equals(this.beta, fundamentalInst.beta) &&
        Objects.equals(this.vol1DayAvg, fundamentalInst.vol1DayAvg) &&
        Objects.equals(this.vol10DayAvg, fundamentalInst.vol10DayAvg) &&
        Objects.equals(this.vol3MonthAvg, fundamentalInst.vol3MonthAvg) &&
        Objects.equals(this.avg10DaysVolume, fundamentalInst.avg10DaysVolume) &&
        Objects.equals(this.avg1DayVolume, fundamentalInst.avg1DayVolume) &&
        Objects.equals(this.avg3MonthVolume, fundamentalInst.avg3MonthVolume) &&
        Objects.equals(this.declarationDate, fundamentalInst.declarationDate) &&
        Objects.equals(this.dividendFreq, fundamentalInst.dividendFreq) &&
        Objects.equals(this.eps, fundamentalInst.eps) &&
        Objects.equals(this.corpactionDate, fundamentalInst.corpactionDate) &&
        Objects.equals(this.dtnVolume, fundamentalInst.dtnVolume) &&
        Objects.equals(this.nextDividendPayDate, fundamentalInst.nextDividendPayDate) &&
        Objects.equals(this.nextDividendDate, fundamentalInst.nextDividendDate) &&
        Objects.equals(this.fundLeverageFactor, fundamentalInst.fundLeverageFactor) &&
        Objects.equals(this.fundStrategy, fundamentalInst.fundStrategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, high52, low52, dividendAmount, dividendYield, dividendDate, peRatio, pegRatio, pbRatio, prRatio, pcfRatio, grossMarginTTM, grossMarginMRQ, netProfitMarginTTM, netProfitMarginMRQ, operatingMarginTTM, operatingMarginMRQ, returnOnEquity, returnOnAssets, returnOnInvestment, quickRatio, currentRatio, interestCoverage, totalDebtToCapital, ltDebtToEquity, totalDebtToEquity, epsTTM, epsChangePercentTTM, epsChangeYear, epsChange, revChangeYear, revChangeTTM, revChangeIn, sharesOutstanding, marketCapFloat, marketCap, bookValuePerShare, shortIntToFloat, shortIntDayToCover, divGrowthRate3Year, dividendPayAmount, dividendPayDate, beta, vol1DayAvg, vol10DayAvg, vol3MonthAvg, avg10DaysVolume, avg1DayVolume, avg3MonthVolume, declarationDate, dividendFreq, eps, corpactionDate, dtnVolume, nextDividendPayDate, nextDividendDate, fundLeverageFactor, fundStrategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundamentalInst {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    high52: ").append(toIndentedString(high52)).append("\n");
    sb.append("    low52: ").append(toIndentedString(low52)).append("\n");
    sb.append("    dividendAmount: ").append(toIndentedString(dividendAmount)).append("\n");
    sb.append("    dividendYield: ").append(toIndentedString(dividendYield)).append("\n");
    sb.append("    dividendDate: ").append(toIndentedString(dividendDate)).append("\n");
    sb.append("    peRatio: ").append(toIndentedString(peRatio)).append("\n");
    sb.append("    pegRatio: ").append(toIndentedString(pegRatio)).append("\n");
    sb.append("    pbRatio: ").append(toIndentedString(pbRatio)).append("\n");
    sb.append("    prRatio: ").append(toIndentedString(prRatio)).append("\n");
    sb.append("    pcfRatio: ").append(toIndentedString(pcfRatio)).append("\n");
    sb.append("    grossMarginTTM: ").append(toIndentedString(grossMarginTTM)).append("\n");
    sb.append("    grossMarginMRQ: ").append(toIndentedString(grossMarginMRQ)).append("\n");
    sb.append("    netProfitMarginTTM: ").append(toIndentedString(netProfitMarginTTM)).append("\n");
    sb.append("    netProfitMarginMRQ: ").append(toIndentedString(netProfitMarginMRQ)).append("\n");
    sb.append("    operatingMarginTTM: ").append(toIndentedString(operatingMarginTTM)).append("\n");
    sb.append("    operatingMarginMRQ: ").append(toIndentedString(operatingMarginMRQ)).append("\n");
    sb.append("    returnOnEquity: ").append(toIndentedString(returnOnEquity)).append("\n");
    sb.append("    returnOnAssets: ").append(toIndentedString(returnOnAssets)).append("\n");
    sb.append("    returnOnInvestment: ").append(toIndentedString(returnOnInvestment)).append("\n");
    sb.append("    quickRatio: ").append(toIndentedString(quickRatio)).append("\n");
    sb.append("    currentRatio: ").append(toIndentedString(currentRatio)).append("\n");
    sb.append("    interestCoverage: ").append(toIndentedString(interestCoverage)).append("\n");
    sb.append("    totalDebtToCapital: ").append(toIndentedString(totalDebtToCapital)).append("\n");
    sb.append("    ltDebtToEquity: ").append(toIndentedString(ltDebtToEquity)).append("\n");
    sb.append("    totalDebtToEquity: ").append(toIndentedString(totalDebtToEquity)).append("\n");
    sb.append("    epsTTM: ").append(toIndentedString(epsTTM)).append("\n");
    sb.append("    epsChangePercentTTM: ").append(toIndentedString(epsChangePercentTTM)).append("\n");
    sb.append("    epsChangeYear: ").append(toIndentedString(epsChangeYear)).append("\n");
    sb.append("    epsChange: ").append(toIndentedString(epsChange)).append("\n");
    sb.append("    revChangeYear: ").append(toIndentedString(revChangeYear)).append("\n");
    sb.append("    revChangeTTM: ").append(toIndentedString(revChangeTTM)).append("\n");
    sb.append("    revChangeIn: ").append(toIndentedString(revChangeIn)).append("\n");
    sb.append("    sharesOutstanding: ").append(toIndentedString(sharesOutstanding)).append("\n");
    sb.append("    marketCapFloat: ").append(toIndentedString(marketCapFloat)).append("\n");
    sb.append("    marketCap: ").append(toIndentedString(marketCap)).append("\n");
    sb.append("    bookValuePerShare: ").append(toIndentedString(bookValuePerShare)).append("\n");
    sb.append("    shortIntToFloat: ").append(toIndentedString(shortIntToFloat)).append("\n");
    sb.append("    shortIntDayToCover: ").append(toIndentedString(shortIntDayToCover)).append("\n");
    sb.append("    divGrowthRate3Year: ").append(toIndentedString(divGrowthRate3Year)).append("\n");
    sb.append("    dividendPayAmount: ").append(toIndentedString(dividendPayAmount)).append("\n");
    sb.append("    dividendPayDate: ").append(toIndentedString(dividendPayDate)).append("\n");
    sb.append("    beta: ").append(toIndentedString(beta)).append("\n");
    sb.append("    vol1DayAvg: ").append(toIndentedString(vol1DayAvg)).append("\n");
    sb.append("    vol10DayAvg: ").append(toIndentedString(vol10DayAvg)).append("\n");
    sb.append("    vol3MonthAvg: ").append(toIndentedString(vol3MonthAvg)).append("\n");
    sb.append("    avg10DaysVolume: ").append(toIndentedString(avg10DaysVolume)).append("\n");
    sb.append("    avg1DayVolume: ").append(toIndentedString(avg1DayVolume)).append("\n");
    sb.append("    avg3MonthVolume: ").append(toIndentedString(avg3MonthVolume)).append("\n");
    sb.append("    declarationDate: ").append(toIndentedString(declarationDate)).append("\n");
    sb.append("    dividendFreq: ").append(toIndentedString(dividendFreq)).append("\n");
    sb.append("    eps: ").append(toIndentedString(eps)).append("\n");
    sb.append("    corpactionDate: ").append(toIndentedString(corpactionDate)).append("\n");
    sb.append("    dtnVolume: ").append(toIndentedString(dtnVolume)).append("\n");
    sb.append("    nextDividendPayDate: ").append(toIndentedString(nextDividendPayDate)).append("\n");
    sb.append("    nextDividendDate: ").append(toIndentedString(nextDividendDate)).append("\n");
    sb.append("    fundLeverageFactor: ").append(toIndentedString(fundLeverageFactor)).append("\n");
    sb.append("    fundStrategy: ").append(toIndentedString(fundStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
