/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FundStrategy \&quot;A\&quot; - Active \&quot;L\&quot; - Leveraged \&quot;P\&quot; - Passive \&quot;Q\&quot; - Quantitative \&quot;S\&quot; - Short
 */
public enum FundStrategy {
  A("A"),
  L("L"),
  P("P"),
  Q("Q"),
  S("S"),
  NULL(null);

  private String value;

  FundStrategy(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FundStrategy fromValue(String input) {
    for (FundStrategy b : FundStrategy.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
