/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.Screener;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse200
 */



public class InlineResponse200 {
  @JsonProperty("screeners")
  private List<Screener> screeners = null;

  public InlineResponse200 screeners(List<Screener> screeners) {
    this.screeners = screeners;
    return this;
  }

  public InlineResponse200 addScreenersItem(Screener screenersItem) {
    if (this.screeners == null) {
      this.screeners = new ArrayList<>();
    }
    this.screeners.add(screenersItem);
    return this;
  }

   /**
   * Get screeners
   * @return screeners
  **/
  @Schema(description = "")
  public List<Screener> getScreeners() {
    return screeners;
  }

  public void setScreeners(List<Screener> screeners) {
    this.screeners = screeners;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.screeners, inlineResponse200.screeners);
  }

  @Override
  public int hashCode() {
    return Objects.hash(screeners);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    screeners: ").append(toIndentedString(screeners)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
