/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Quote data of Future security
 */
@Schema(description = "Quote data of Future security")


public class QuoteFuture {
  @JsonProperty("askMICId")
  private String askMICId = null;

  @JsonProperty("askPrice")
  private Double askPrice = null;

  @JsonProperty("askSize")
  private Integer askSize = null;

  @JsonProperty("askTime")
  private Long askTime = null;

  @JsonProperty("bidMICId")
  private String bidMICId = null;

  @JsonProperty("bidPrice")
  private Double bidPrice = null;

  @JsonProperty("bidSize")
  private Integer bidSize = null;

  @JsonProperty("bidTime")
  private Long bidTime = null;

  @JsonProperty("closePrice")
  private Double closePrice = null;

  @JsonProperty("futurePercentChange")
  private Double futurePercentChange = null;

  @JsonProperty("highPrice")
  private Double highPrice = null;

  @JsonProperty("lastMICId")
  private String lastMICId = null;

  @JsonProperty("lastPrice")
  private Double lastPrice = null;

  @JsonProperty("lastSize")
  private Integer lastSize = null;

  @JsonProperty("lowPrice")
  private Double lowPrice = null;

  @JsonProperty("mark")
  private Double mark = null;

  @JsonProperty("netChange")
  private Double netChange = null;

  @JsonProperty("openInterest")
  private Integer openInterest = null;

  @JsonProperty("openPrice")
  private Double openPrice = null;

  @JsonProperty("quoteTime")
  private Long quoteTime = null;

  @JsonProperty("quotedInSession")
  private Boolean quotedInSession = null;

  @JsonProperty("securityStatus")
  private String securityStatus = null;

  @JsonProperty("settleTime")
  private Long settleTime = null;

  @JsonProperty("tick")
  private Double tick = null;

  @JsonProperty("tickAmount")
  private Double tickAmount = null;

  @JsonProperty("totalVolume")
  private Long totalVolume = null;

  @JsonProperty("tradeTime")
  private Long tradeTime = null;

  public QuoteFuture askMICId(String askMICId) {
    this.askMICId = askMICId;
    return this;
  }

   /**
   * ask MIC code
   * @return askMICId
  **/
  @Schema(example = "XNYS", description = "ask MIC code")
  public String getAskMICId() {
    return askMICId;
  }

  public void setAskMICId(String askMICId) {
    this.askMICId = askMICId;
  }

  public QuoteFuture askPrice(Double askPrice) {
    this.askPrice = askPrice;
    return this;
  }

   /**
   * Current Best Ask Price
   * @return askPrice
  **/
  @Schema(example = "4083.25", description = "Current Best Ask Price")
  public Double getAskPrice() {
    return askPrice;
  }

  public void setAskPrice(Double askPrice) {
    this.askPrice = askPrice;
  }

  public QuoteFuture askSize(Integer askSize) {
    this.askSize = askSize;
    return this;
  }

   /**
   * Number of shares for ask
   * @return askSize
  **/
  @Schema(example = "36", description = "Number of shares for ask")
  public Integer getAskSize() {
    return askSize;
  }

  public void setAskSize(Integer askSize) {
    this.askSize = askSize;
  }

  public QuoteFuture askTime(Long askTime) {
    this.askTime = askTime;
    return this;
  }

   /**
   * Last ask time in milliseconds since Epoch
   * @return askTime
  **/
  @Schema(example = "1621376892336", description = "Last ask time in milliseconds since Epoch")
  public Long getAskTime() {
    return askTime;
  }

  public void setAskTime(Long askTime) {
    this.askTime = askTime;
  }

  public QuoteFuture bidMICId(String bidMICId) {
    this.bidMICId = bidMICId;
    return this;
  }

   /**
   * bid MIC code
   * @return bidMICId
  **/
  @Schema(example = "XNYS", description = "bid MIC code")
  public String getBidMICId() {
    return bidMICId;
  }

  public void setBidMICId(String bidMICId) {
    this.bidMICId = bidMICId;
  }

  public QuoteFuture bidPrice(Double bidPrice) {
    this.bidPrice = bidPrice;
    return this;
  }

   /**
   * Current Best Bid Price
   * @return bidPrice
  **/
  @Schema(example = "4083", description = "Current Best Bid Price")
  public Double getBidPrice() {
    return bidPrice;
  }

  public void setBidPrice(Double bidPrice) {
    this.bidPrice = bidPrice;
  }

  public QuoteFuture bidSize(Integer bidSize) {
    this.bidSize = bidSize;
    return this;
  }

   /**
   * Number of shares for bid
   * @return bidSize
  **/
  @Schema(example = "18", description = "Number of shares for bid")
  public Integer getBidSize() {
    return bidSize;
  }

  public void setBidSize(Integer bidSize) {
    this.bidSize = bidSize;
  }

  public QuoteFuture bidTime(Long bidTime) {
    this.bidTime = bidTime;
    return this;
  }

   /**
   * Last bid time in milliseconds since Epoch
   * @return bidTime
  **/
  @Schema(example = "1621376892336", description = "Last bid time in milliseconds since Epoch")
  public Long getBidTime() {
    return bidTime;
  }

  public void setBidTime(Long bidTime) {
    this.bidTime = bidTime;
  }

  public QuoteFuture closePrice(Double closePrice) {
    this.closePrice = closePrice;
    return this;
  }

   /**
   * Previous day&#x27;s closing price
   * @return closePrice
  **/
  @Schema(example = "4123", description = "Previous day's closing price")
  public Double getClosePrice() {
    return closePrice;
  }

  public void setClosePrice(Double closePrice) {
    this.closePrice = closePrice;
  }

  public QuoteFuture futurePercentChange(Double futurePercentChange) {
    this.futurePercentChange = futurePercentChange;
    return this;
  }

   /**
   * Net Percentage Change
   * @return futurePercentChange
  **/
  @Schema(example = "-0.0756", description = "Net Percentage Change")
  public Double getFuturePercentChange() {
    return futurePercentChange;
  }

  public void setFuturePercentChange(Double futurePercentChange) {
    this.futurePercentChange = futurePercentChange;
  }

  public QuoteFuture highPrice(Double highPrice) {
    this.highPrice = highPrice;
    return this;
  }

   /**
   * Day&#x27;s high trade price
   * @return highPrice
  **/
  @Schema(example = "4123", description = "Day's high trade price")
  public Double getHighPrice() {
    return highPrice;
  }

  public void setHighPrice(Double highPrice) {
    this.highPrice = highPrice;
  }

  public QuoteFuture lastMICId(String lastMICId) {
    this.lastMICId = lastMICId;
    return this;
  }

   /**
   * Last MIC Code
   * @return lastMICId
  **/
  @Schema(example = "XNYS", description = "Last MIC Code")
  public String getLastMICId() {
    return lastMICId;
  }

  public void setLastMICId(String lastMICId) {
    this.lastMICId = lastMICId;
  }

  public QuoteFuture lastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  @Schema(example = "4083", description = "")
  public Double getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
  }

  public QuoteFuture lastSize(Integer lastSize) {
    this.lastSize = lastSize;
    return this;
  }

   /**
   * Number of shares traded with last trade
   * @return lastSize
  **/
  @Schema(example = "7", description = "Number of shares traded with last trade")
  public Integer getLastSize() {
    return lastSize;
  }

  public void setLastSize(Integer lastSize) {
    this.lastSize = lastSize;
  }

  public QuoteFuture lowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
    return this;
  }

   /**
   * Day&#x27;s low trade price
   * @return lowPrice
  **/
  @Schema(example = "4075.5", description = "Day's low trade price")
  public Double getLowPrice() {
    return lowPrice;
  }

  public void setLowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
  }

  public QuoteFuture mark(Double mark) {
    this.mark = mark;
    return this;
  }

   /**
   * Mark price
   * @return mark
  **/
  @Schema(example = "4083", description = "Mark price")
  public Double getMark() {
    return mark;
  }

  public void setMark(Double mark) {
    this.mark = mark;
  }

  public QuoteFuture netChange(Double netChange) {
    this.netChange = netChange;
    return this;
  }

   /**
   * Current Last-Prev Close
   * @return netChange
  **/
  @Schema(example = "-40", description = "Current Last-Prev Close")
  public Double getNetChange() {
    return netChange;
  }

  public void setNetChange(Double netChange) {
    this.netChange = netChange;
  }

  public QuoteFuture openInterest(Integer openInterest) {
    this.openInterest = openInterest;
    return this;
  }

   /**
   * Open interest
   * @return openInterest
  **/
  @Schema(example = "2517139", description = "Open interest")
  public Integer getOpenInterest() {
    return openInterest;
  }

  public void setOpenInterest(Integer openInterest) {
    this.openInterest = openInterest;
  }

  public QuoteFuture openPrice(Double openPrice) {
    this.openPrice = openPrice;
    return this;
  }

   /**
   * Price at market open
   * @return openPrice
  **/
  @Schema(example = "4114", description = "Price at market open")
  public Double getOpenPrice() {
    return openPrice;
  }

  public void setOpenPrice(Double openPrice) {
    this.openPrice = openPrice;
  }

  public QuoteFuture quoteTime(Long quoteTime) {
    this.quoteTime = quoteTime;
    return this;
  }

   /**
   * Last quote time in milliseconds since Epoch
   * @return quoteTime
  **/
  @Schema(example = "1621427004585", description = "Last quote time in milliseconds since Epoch")
  public Long getQuoteTime() {
    return quoteTime;
  }

  public void setQuoteTime(Long quoteTime) {
    this.quoteTime = quoteTime;
  }

  public QuoteFuture quotedInSession(Boolean quotedInSession) {
    this.quotedInSession = quotedInSession;
    return this;
  }

   /**
   * quoted during trading session
   * @return quotedInSession
  **/
  @Schema(example = "false", description = "quoted during trading session")
  public Boolean isQuotedInSession() {
    return quotedInSession;
  }

  public void setQuotedInSession(Boolean quotedInSession) {
    this.quotedInSession = quotedInSession;
  }

  public QuoteFuture securityStatus(String securityStatus) {
    this.securityStatus = securityStatus;
    return this;
  }

   /**
   * Status of security
   * @return securityStatus
  **/
  @Schema(example = "Normal", description = "Status of security")
  public String getSecurityStatus() {
    return securityStatus;
  }

  public void setSecurityStatus(String securityStatus) {
    this.securityStatus = securityStatus;
  }

  public QuoteFuture settleTime(Long settleTime) {
    this.settleTime = settleTime;
    return this;
  }

   /**
   * settlement time in milliseconds since Epoch
   * @return settleTime
  **/
  @Schema(example = "1621376892336", description = "settlement time in milliseconds since Epoch")
  public Long getSettleTime() {
    return settleTime;
  }

  public void setSettleTime(Long settleTime) {
    this.settleTime = settleTime;
  }

  public QuoteFuture tick(Double tick) {
    this.tick = tick;
    return this;
  }

   /**
   * Tick Price
   * @return tick
  **/
  @Schema(example = "0.25", description = "Tick Price")
  public Double getTick() {
    return tick;
  }

  public void setTick(Double tick) {
    this.tick = tick;
  }

  public QuoteFuture tickAmount(Double tickAmount) {
    this.tickAmount = tickAmount;
    return this;
  }

   /**
   * Tick Amount
   * @return tickAmount
  **/
  @Schema(example = "12.5", description = "Tick Amount")
  public Double getTickAmount() {
    return tickAmount;
  }

  public void setTickAmount(Double tickAmount) {
    this.tickAmount = tickAmount;
  }

  public QuoteFuture totalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
    return this;
  }

   /**
   * Aggregated shares traded throughout the day, including pre/post market hours.
   * @return totalVolume
  **/
  @Schema(example = "20171188", description = "Aggregated shares traded throughout the day, including pre/post market hours.")
  public Long getTotalVolume() {
    return totalVolume;
  }

  public void setTotalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
  }

  public QuoteFuture tradeTime(Long tradeTime) {
    this.tradeTime = tradeTime;
    return this;
  }

   /**
   * Last trade time in milliseconds since Epoch
   * @return tradeTime
  **/
  @Schema(example = "1621376731304", description = "Last trade time in milliseconds since Epoch")
  public Long getTradeTime() {
    return tradeTime;
  }

  public void setTradeTime(Long tradeTime) {
    this.tradeTime = tradeTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteFuture quoteFuture = (QuoteFuture) o;
    return Objects.equals(this.askMICId, quoteFuture.askMICId) &&
        Objects.equals(this.askPrice, quoteFuture.askPrice) &&
        Objects.equals(this.askSize, quoteFuture.askSize) &&
        Objects.equals(this.askTime, quoteFuture.askTime) &&
        Objects.equals(this.bidMICId, quoteFuture.bidMICId) &&
        Objects.equals(this.bidPrice, quoteFuture.bidPrice) &&
        Objects.equals(this.bidSize, quoteFuture.bidSize) &&
        Objects.equals(this.bidTime, quoteFuture.bidTime) &&
        Objects.equals(this.closePrice, quoteFuture.closePrice) &&
        Objects.equals(this.futurePercentChange, quoteFuture.futurePercentChange) &&
        Objects.equals(this.highPrice, quoteFuture.highPrice) &&
        Objects.equals(this.lastMICId, quoteFuture.lastMICId) &&
        Objects.equals(this.lastPrice, quoteFuture.lastPrice) &&
        Objects.equals(this.lastSize, quoteFuture.lastSize) &&
        Objects.equals(this.lowPrice, quoteFuture.lowPrice) &&
        Objects.equals(this.mark, quoteFuture.mark) &&
        Objects.equals(this.netChange, quoteFuture.netChange) &&
        Objects.equals(this.openInterest, quoteFuture.openInterest) &&
        Objects.equals(this.openPrice, quoteFuture.openPrice) &&
        Objects.equals(this.quoteTime, quoteFuture.quoteTime) &&
        Objects.equals(this.quotedInSession, quoteFuture.quotedInSession) &&
        Objects.equals(this.securityStatus, quoteFuture.securityStatus) &&
        Objects.equals(this.settleTime, quoteFuture.settleTime) &&
        Objects.equals(this.tick, quoteFuture.tick) &&
        Objects.equals(this.tickAmount, quoteFuture.tickAmount) &&
        Objects.equals(this.totalVolume, quoteFuture.totalVolume) &&
        Objects.equals(this.tradeTime, quoteFuture.tradeTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(askMICId, askPrice, askSize, askTime, bidMICId, bidPrice, bidSize, bidTime, closePrice, futurePercentChange, highPrice, lastMICId, lastPrice, lastSize, lowPrice, mark, netChange, openInterest, openPrice, quoteTime, quotedInSession, securityStatus, settleTime, tick, tickAmount, totalVolume, tradeTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteFuture {\n");
    
    sb.append("    askMICId: ").append(toIndentedString(askMICId)).append("\n");
    sb.append("    askPrice: ").append(toIndentedString(askPrice)).append("\n");
    sb.append("    askSize: ").append(toIndentedString(askSize)).append("\n");
    sb.append("    askTime: ").append(toIndentedString(askTime)).append("\n");
    sb.append("    bidMICId: ").append(toIndentedString(bidMICId)).append("\n");
    sb.append("    bidPrice: ").append(toIndentedString(bidPrice)).append("\n");
    sb.append("    bidSize: ").append(toIndentedString(bidSize)).append("\n");
    sb.append("    bidTime: ").append(toIndentedString(bidTime)).append("\n");
    sb.append("    closePrice: ").append(toIndentedString(closePrice)).append("\n");
    sb.append("    futurePercentChange: ").append(toIndentedString(futurePercentChange)).append("\n");
    sb.append("    highPrice: ").append(toIndentedString(highPrice)).append("\n");
    sb.append("    lastMICId: ").append(toIndentedString(lastMICId)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    lastSize: ").append(toIndentedString(lastSize)).append("\n");
    sb.append("    lowPrice: ").append(toIndentedString(lowPrice)).append("\n");
    sb.append("    mark: ").append(toIndentedString(mark)).append("\n");
    sb.append("    netChange: ").append(toIndentedString(netChange)).append("\n");
    sb.append("    openInterest: ").append(toIndentedString(openInterest)).append("\n");
    sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
    sb.append("    quoteTime: ").append(toIndentedString(quoteTime)).append("\n");
    sb.append("    quotedInSession: ").append(toIndentedString(quotedInSession)).append("\n");
    sb.append("    securityStatus: ").append(toIndentedString(securityStatus)).append("\n");
    sb.append("    settleTime: ").append(toIndentedString(settleTime)).append("\n");
    sb.append("    tick: ").append(toIndentedString(tick)).append("\n");
    sb.append("    tickAmount: ").append(toIndentedString(tickAmount)).append("\n");
    sb.append("    totalVolume: ").append(toIndentedString(totalVolume)).append("\n");
    sb.append("    tradeTime: ").append(toIndentedString(tradeTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
