/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Quote data of Equity security
 */
@Schema(description = "Quote data of Equity security")


public class QuoteEquity {
  @JsonProperty("52WeekHigh")
  private Double _52WeekHigh = null;

  @JsonProperty("52WeekLow")
  private Double _52WeekLow = null;

  @JsonProperty("askMICId")
  private String askMICId = null;

  @JsonProperty("askPrice")
  private Double askPrice = null;

  @JsonProperty("askSize")
  private Integer askSize = null;

  @JsonProperty("askTime")
  private Long askTime = null;

  @JsonProperty("bidMICId")
  private String bidMICId = null;

  @JsonProperty("bidPrice")
  private Double bidPrice = null;

  @JsonProperty("bidSize")
  private Integer bidSize = null;

  @JsonProperty("bidTime")
  private Long bidTime = null;

  @JsonProperty("closePrice")
  private Double closePrice = null;

  @JsonProperty("highPrice")
  private Double highPrice = null;

  @JsonProperty("lastMICId")
  private String lastMICId = null;

  @JsonProperty("lastPrice")
  private Double lastPrice = null;

  @JsonProperty("lastSize")
  private Integer lastSize = null;

  @JsonProperty("lowPrice")
  private Double lowPrice = null;

  @JsonProperty("mark")
  private Double mark = null;

  @JsonProperty("markChange")
  private Double markChange = null;

  @JsonProperty("markPercentChange")
  private Double markPercentChange = null;

  @JsonProperty("netChange")
  private Double netChange = null;

  @JsonProperty("netPercentChange")
  private Double netPercentChange = null;

  @JsonProperty("openPrice")
  private Double openPrice = null;

  @JsonProperty("quoteTime")
  private Long quoteTime = null;

  @JsonProperty("securityStatus")
  private String securityStatus = null;

  @JsonProperty("totalVolume")
  private Long totalVolume = null;

  @JsonProperty("tradeTime")
  private Long tradeTime = null;

  @JsonProperty("volatility")
  private Double volatility = null;

  public QuoteEquity _52WeekHigh(Double _52WeekHigh) {
    this._52WeekHigh = _52WeekHigh;
    return this;
  }

   /**
   * Higest price traded in the past 12 months, or 52 weeks
   * @return _52WeekHigh
  **/
  @Schema(example = "145.09", description = "Higest price traded in the past 12 months, or 52 weeks")
  public Double get52WeekHigh() {
    return _52WeekHigh;
  }

  public void set52WeekHigh(Double _52WeekHigh) {
    this._52WeekHigh = _52WeekHigh;
  }

  public QuoteEquity _52WeekLow(Double _52WeekLow) {
    this._52WeekLow = _52WeekLow;
    return this;
  }

   /**
   * Lowest price traded in the past 12 months, or 52 weeks
   * @return _52WeekLow
  **/
  @Schema(example = "77.581", description = "Lowest price traded in the past 12 months, or 52 weeks")
  public Double get52WeekLow() {
    return _52WeekLow;
  }

  public void set52WeekLow(Double _52WeekLow) {
    this._52WeekLow = _52WeekLow;
  }

  public QuoteEquity askMICId(String askMICId) {
    this.askMICId = askMICId;
    return this;
  }

   /**
   * ask MIC code
   * @return askMICId
  **/
  @Schema(example = "XNYS", description = "ask MIC code")
  public String getAskMICId() {
    return askMICId;
  }

  public void setAskMICId(String askMICId) {
    this.askMICId = askMICId;
  }

  public QuoteEquity askPrice(Double askPrice) {
    this.askPrice = askPrice;
    return this;
  }

   /**
   * Current Best Ask Price
   * @return askPrice
  **/
  @Schema(example = "124.63", description = "Current Best Ask Price")
  public Double getAskPrice() {
    return askPrice;
  }

  public void setAskPrice(Double askPrice) {
    this.askPrice = askPrice;
  }

  public QuoteEquity askSize(Integer askSize) {
    this.askSize = askSize;
    return this;
  }

   /**
   * Number of shares for ask
   * @return askSize
  **/
  @Schema(example = "700", description = "Number of shares for ask")
  public Integer getAskSize() {
    return askSize;
  }

  public void setAskSize(Integer askSize) {
    this.askSize = askSize;
  }

  public QuoteEquity askTime(Long askTime) {
    this.askTime = askTime;
    return this;
  }

   /**
   * Last ask time in milliseconds since Epoch
   * @return askTime
  **/
  @Schema(example = "1621376892336", description = "Last ask time in milliseconds since Epoch")
  public Long getAskTime() {
    return askTime;
  }

  public void setAskTime(Long askTime) {
    this.askTime = askTime;
  }

  public QuoteEquity bidMICId(String bidMICId) {
    this.bidMICId = bidMICId;
    return this;
  }

   /**
   * bid MIC code
   * @return bidMICId
  **/
  @Schema(example = "XNYS", description = "bid MIC code")
  public String getBidMICId() {
    return bidMICId;
  }

  public void setBidMICId(String bidMICId) {
    this.bidMICId = bidMICId;
  }

  public QuoteEquity bidPrice(Double bidPrice) {
    this.bidPrice = bidPrice;
    return this;
  }

   /**
   * Current Best Bid Price
   * @return bidPrice
  **/
  @Schema(example = "124.6", description = "Current Best Bid Price")
  public Double getBidPrice() {
    return bidPrice;
  }

  public void setBidPrice(Double bidPrice) {
    this.bidPrice = bidPrice;
  }

  public QuoteEquity bidSize(Integer bidSize) {
    this.bidSize = bidSize;
    return this;
  }

   /**
   * Number of shares for bid
   * @return bidSize
  **/
  @Schema(example = "300", description = "Number of shares for bid")
  public Integer getBidSize() {
    return bidSize;
  }

  public void setBidSize(Integer bidSize) {
    this.bidSize = bidSize;
  }

  public QuoteEquity bidTime(Long bidTime) {
    this.bidTime = bidTime;
    return this;
  }

   /**
   * Last bid time in milliseconds since Epoch
   * @return bidTime
  **/
  @Schema(example = "1621376892336", description = "Last bid time in milliseconds since Epoch")
  public Long getBidTime() {
    return bidTime;
  }

  public void setBidTime(Long bidTime) {
    this.bidTime = bidTime;
  }

  public QuoteEquity closePrice(Double closePrice) {
    this.closePrice = closePrice;
    return this;
  }

   /**
   * Previous day&#x27;s closing price
   * @return closePrice
  **/
  @Schema(example = "126.27", description = "Previous day's closing price")
  public Double getClosePrice() {
    return closePrice;
  }

  public void setClosePrice(Double closePrice) {
    this.closePrice = closePrice;
  }

  public QuoteEquity highPrice(Double highPrice) {
    this.highPrice = highPrice;
    return this;
  }

   /**
   * Day&#x27;s high trade price
   * @return highPrice
  **/
  @Schema(example = "126.99", description = "Day's high trade price")
  public Double getHighPrice() {
    return highPrice;
  }

  public void setHighPrice(Double highPrice) {
    this.highPrice = highPrice;
  }

  public QuoteEquity lastMICId(String lastMICId) {
    this.lastMICId = lastMICId;
    return this;
  }

   /**
   * Last MIC Code
   * @return lastMICId
  **/
  @Schema(example = "XNYS", description = "Last MIC Code")
  public String getLastMICId() {
    return lastMICId;
  }

  public void setLastMICId(String lastMICId) {
    this.lastMICId = lastMICId;
  }

  public QuoteEquity lastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  @Schema(example = "122.3", description = "")
  public Double getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
  }

  public QuoteEquity lastSize(Integer lastSize) {
    this.lastSize = lastSize;
    return this;
  }

   /**
   * Number of shares traded with last trade
   * @return lastSize
  **/
  @Schema(example = "100", description = "Number of shares traded with last trade")
  public Integer getLastSize() {
    return lastSize;
  }

  public void setLastSize(Integer lastSize) {
    this.lastSize = lastSize;
  }

  public QuoteEquity lowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
    return this;
  }

   /**
   * Day&#x27;s low trade price
   * @return lowPrice
  **/
  @Schema(description = "Day's low trade price")
  public Double getLowPrice() {
    return lowPrice;
  }

  public void setLowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
  }

  public QuoteEquity mark(Double mark) {
    this.mark = mark;
    return this;
  }

   /**
   * Mark price
   * @return mark
  **/
  @Schema(example = "52.93", description = "Mark price")
  public Double getMark() {
    return mark;
  }

  public void setMark(Double mark) {
    this.mark = mark;
  }

  public QuoteEquity markChange(Double markChange) {
    this.markChange = markChange;
    return this;
  }

   /**
   * Mark Price change
   * @return markChange
  **/
  @Schema(example = "-0.01", description = "Mark Price change")
  public Double getMarkChange() {
    return markChange;
  }

  public void setMarkChange(Double markChange) {
    this.markChange = markChange;
  }

  public QuoteEquity markPercentChange(Double markPercentChange) {
    this.markPercentChange = markPercentChange;
    return this;
  }

   /**
   * Mark Price percent change
   * @return markPercentChange
  **/
  @Schema(example = "-0.0189", description = "Mark Price percent change")
  public Double getMarkPercentChange() {
    return markPercentChange;
  }

  public void setMarkPercentChange(Double markPercentChange) {
    this.markPercentChange = markPercentChange;
  }

  public QuoteEquity netChange(Double netChange) {
    this.netChange = netChange;
    return this;
  }

   /**
   * Current Last-Prev Close
   * @return netChange
  **/
  @Schema(example = "-0.04", description = "Current Last-Prev Close")
  public Double getNetChange() {
    return netChange;
  }

  public void setNetChange(Double netChange) {
    this.netChange = netChange;
  }

  public QuoteEquity netPercentChange(Double netPercentChange) {
    this.netPercentChange = netPercentChange;
    return this;
  }

   /**
   * Net Percentage Change
   * @return netPercentChange
  **/
  @Schema(example = "-0.0756", description = "Net Percentage Change")
  public Double getNetPercentChange() {
    return netPercentChange;
  }

  public void setNetPercentChange(Double netPercentChange) {
    this.netPercentChange = netPercentChange;
  }

  public QuoteEquity openPrice(Double openPrice) {
    this.openPrice = openPrice;
    return this;
  }

   /**
   * Price at market open
   * @return openPrice
  **/
  @Schema(example = "52.8", description = "Price at market open")
  public Double getOpenPrice() {
    return openPrice;
  }

  public void setOpenPrice(Double openPrice) {
    this.openPrice = openPrice;
  }

  public QuoteEquity quoteTime(Long quoteTime) {
    this.quoteTime = quoteTime;
    return this;
  }

   /**
   * Last quote time in milliseconds since Epoch
   * @return quoteTime
  **/
  @Schema(example = "1621376892336", description = "Last quote time in milliseconds since Epoch")
  public Long getQuoteTime() {
    return quoteTime;
  }

  public void setQuoteTime(Long quoteTime) {
    this.quoteTime = quoteTime;
  }

  public QuoteEquity securityStatus(String securityStatus) {
    this.securityStatus = securityStatus;
    return this;
  }

   /**
   * Status of security
   * @return securityStatus
  **/
  @Schema(example = "Normal", description = "Status of security")
  public String getSecurityStatus() {
    return securityStatus;
  }

  public void setSecurityStatus(String securityStatus) {
    this.securityStatus = securityStatus;
  }

  public QuoteEquity totalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
    return this;
  }

   /**
   * Aggregated shares traded throughout the day, including pre/post market hours.
   * @return totalVolume
  **/
  @Schema(example = "20171188", description = "Aggregated shares traded throughout the day, including pre/post market hours.")
  public Long getTotalVolume() {
    return totalVolume;
  }

  public void setTotalVolume(Long totalVolume) {
    this.totalVolume = totalVolume;
  }

  public QuoteEquity tradeTime(Long tradeTime) {
    this.tradeTime = tradeTime;
    return this;
  }

   /**
   * Last trade time in milliseconds since Epoch
   * @return tradeTime
  **/
  @Schema(example = "1621376731304", description = "Last trade time in milliseconds since Epoch")
  public Long getTradeTime() {
    return tradeTime;
  }

  public void setTradeTime(Long tradeTime) {
    this.tradeTime = tradeTime;
  }

  public QuoteEquity volatility(Double volatility) {
    this.volatility = volatility;
    return this;
  }

   /**
   * Option Risk/Volatility Measurement
   * @return volatility
  **/
  @Schema(example = "0.0094", description = "Option Risk/Volatility Measurement")
  public Double getVolatility() {
    return volatility;
  }

  public void setVolatility(Double volatility) {
    this.volatility = volatility;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteEquity quoteEquity = (QuoteEquity) o;
    return Objects.equals(this._52WeekHigh, quoteEquity._52WeekHigh) &&
        Objects.equals(this._52WeekLow, quoteEquity._52WeekLow) &&
        Objects.equals(this.askMICId, quoteEquity.askMICId) &&
        Objects.equals(this.askPrice, quoteEquity.askPrice) &&
        Objects.equals(this.askSize, quoteEquity.askSize) &&
        Objects.equals(this.askTime, quoteEquity.askTime) &&
        Objects.equals(this.bidMICId, quoteEquity.bidMICId) &&
        Objects.equals(this.bidPrice, quoteEquity.bidPrice) &&
        Objects.equals(this.bidSize, quoteEquity.bidSize) &&
        Objects.equals(this.bidTime, quoteEquity.bidTime) &&
        Objects.equals(this.closePrice, quoteEquity.closePrice) &&
        Objects.equals(this.highPrice, quoteEquity.highPrice) &&
        Objects.equals(this.lastMICId, quoteEquity.lastMICId) &&
        Objects.equals(this.lastPrice, quoteEquity.lastPrice) &&
        Objects.equals(this.lastSize, quoteEquity.lastSize) &&
        Objects.equals(this.lowPrice, quoteEquity.lowPrice) &&
        Objects.equals(this.mark, quoteEquity.mark) &&
        Objects.equals(this.markChange, quoteEquity.markChange) &&
        Objects.equals(this.markPercentChange, quoteEquity.markPercentChange) &&
        Objects.equals(this.netChange, quoteEquity.netChange) &&
        Objects.equals(this.netPercentChange, quoteEquity.netPercentChange) &&
        Objects.equals(this.openPrice, quoteEquity.openPrice) &&
        Objects.equals(this.quoteTime, quoteEquity.quoteTime) &&
        Objects.equals(this.securityStatus, quoteEquity.securityStatus) &&
        Objects.equals(this.totalVolume, quoteEquity.totalVolume) &&
        Objects.equals(this.tradeTime, quoteEquity.tradeTime) &&
        Objects.equals(this.volatility, quoteEquity.volatility);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_52WeekHigh, _52WeekLow, askMICId, askPrice, askSize, askTime, bidMICId, bidPrice, bidSize, bidTime, closePrice, highPrice, lastMICId, lastPrice, lastSize, lowPrice, mark, markChange, markPercentChange, netChange, netPercentChange, openPrice, quoteTime, securityStatus, totalVolume, tradeTime, volatility);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteEquity {\n");
    
    sb.append("    _52WeekHigh: ").append(toIndentedString(_52WeekHigh)).append("\n");
    sb.append("    _52WeekLow: ").append(toIndentedString(_52WeekLow)).append("\n");
    sb.append("    askMICId: ").append(toIndentedString(askMICId)).append("\n");
    sb.append("    askPrice: ").append(toIndentedString(askPrice)).append("\n");
    sb.append("    askSize: ").append(toIndentedString(askSize)).append("\n");
    sb.append("    askTime: ").append(toIndentedString(askTime)).append("\n");
    sb.append("    bidMICId: ").append(toIndentedString(bidMICId)).append("\n");
    sb.append("    bidPrice: ").append(toIndentedString(bidPrice)).append("\n");
    sb.append("    bidSize: ").append(toIndentedString(bidSize)).append("\n");
    sb.append("    bidTime: ").append(toIndentedString(bidTime)).append("\n");
    sb.append("    closePrice: ").append(toIndentedString(closePrice)).append("\n");
    sb.append("    highPrice: ").append(toIndentedString(highPrice)).append("\n");
    sb.append("    lastMICId: ").append(toIndentedString(lastMICId)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    lastSize: ").append(toIndentedString(lastSize)).append("\n");
    sb.append("    lowPrice: ").append(toIndentedString(lowPrice)).append("\n");
    sb.append("    mark: ").append(toIndentedString(mark)).append("\n");
    sb.append("    markChange: ").append(toIndentedString(markChange)).append("\n");
    sb.append("    markPercentChange: ").append(toIndentedString(markPercentChange)).append("\n");
    sb.append("    netChange: ").append(toIndentedString(netChange)).append("\n");
    sb.append("    netPercentChange: ").append(toIndentedString(netPercentChange)).append("\n");
    sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
    sb.append("    quoteTime: ").append(toIndentedString(quoteTime)).append("\n");
    sb.append("    securityStatus: ").append(toIndentedString(securityStatus)).append("\n");
    sb.append("    totalVolume: ").append(toIndentedString(totalVolume)).append("\n");
    sb.append("    tradeTime: ").append(toIndentedString(tradeTime)).append("\n");
    sb.append("    volatility: ").append(toIndentedString(volatility)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
