/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
* QuoteResponseObject
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "")
@JsonSubTypes({
  @JsonSubTypes.Type(value = EquityResponse.class, name = "EquityResponse"),
  @JsonSubTypes.Type(value = OptionResponse.class, name = "OptionResponse"),
  @JsonSubTypes.Type(value = ForexResponse.class, name = "ForexResponse"),
  @JsonSubTypes.Type(value = FutureResponse.class, name = "FutureResponse"),
  @JsonSubTypes.Type(value = FutureOptionResponse.class, name = "FutureOptionResponse"),
  @JsonSubTypes.Type(value = IndexResponse.class, name = "IndexResponse"),
  @JsonSubTypes.Type(value = MutualFundResponse.class, name = "MutualFundResponse"),
  @JsonSubTypes.Type(value = QuoteError.class, name = "QuoteError")
})
public interface QuoteResponseObject {

}
