/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.ContractType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reference data of Future Option security
 */
@Schema(description = "Reference data of Future Option security")


public class ReferenceFutureOption {
  @JsonProperty("contractType")
  private ContractType contractType = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("exchange")
  private String exchange = null;

  @JsonProperty("exchangeName")
  private String exchangeName = null;

  @JsonProperty("multiplier")
  private Double multiplier = null;

  @JsonProperty("expirationDate")
  private Long expirationDate = null;

  @JsonProperty("expirationStyle")
  private String expirationStyle = null;

  @JsonProperty("strikePrice")
  private Double strikePrice = null;

  @JsonProperty("underlying")
  private String underlying = null;

  public ReferenceFutureOption contractType(ContractType contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  @Schema(description = "")
  public ContractType getContractType() {
    return contractType;
  }

  public void setContractType(ContractType contractType) {
    this.contractType = contractType;
  }

  public ReferenceFutureOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of Instrument
   * @return description
  **/
  @Schema(example = "AMZN Aug 20 2021 2300 Put", description = "Description of Instrument")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReferenceFutureOption exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Exchange Code
   * @return exchange
  **/
  @Schema(example = "q", description = "Exchange Code")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ReferenceFutureOption exchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
    return this;
  }

   /**
   * Exchange Name
   * @return exchangeName
  **/
  @Schema(description = "Exchange Name")
  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }

  public ReferenceFutureOption multiplier(Double multiplier) {
    this.multiplier = multiplier;
    return this;
  }

   /**
   * Option multiplier
   * @return multiplier
  **/
  @Schema(example = "100", description = "Option multiplier")
  public Double getMultiplier() {
    return multiplier;
  }

  public void setMultiplier(Double multiplier) {
    this.multiplier = multiplier;
  }

  public ReferenceFutureOption expirationDate(Long expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * date of expiration in long
   * @return expirationDate
  **/
  @Schema(description = "date of expiration in long")
  public Long getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(Long expirationDate) {
    this.expirationDate = expirationDate;
  }

  public ReferenceFutureOption expirationStyle(String expirationStyle) {
    this.expirationStyle = expirationStyle;
    return this;
  }

   /**
   * Style of expiration
   * @return expirationStyle
  **/
  @Schema(description = "Style of expiration")
  public String getExpirationStyle() {
    return expirationStyle;
  }

  public void setExpirationStyle(String expirationStyle) {
    this.expirationStyle = expirationStyle;
  }

  public ReferenceFutureOption strikePrice(Double strikePrice) {
    this.strikePrice = strikePrice;
    return this;
  }

   /**
   * Strike Price
   * @return strikePrice
  **/
  @Schema(example = "2300", description = "Strike Price")
  public Double getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(Double strikePrice) {
    this.strikePrice = strikePrice;
  }

  public ReferenceFutureOption underlying(String underlying) {
    this.underlying = underlying;
    return this;
  }

   /**
   * A company, index or fund name
   * @return underlying
  **/
  @Schema(example = "AMZN Aug 20 2021 2300 Put", description = "A company, index or fund name")
  public String getUnderlying() {
    return underlying;
  }

  public void setUnderlying(String underlying) {
    this.underlying = underlying;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceFutureOption referenceFutureOption = (ReferenceFutureOption) o;
    return Objects.equals(this.contractType, referenceFutureOption.contractType) &&
        Objects.equals(this.description, referenceFutureOption.description) &&
        Objects.equals(this.exchange, referenceFutureOption.exchange) &&
        Objects.equals(this.exchangeName, referenceFutureOption.exchangeName) &&
        Objects.equals(this.multiplier, referenceFutureOption.multiplier) &&
        Objects.equals(this.expirationDate, referenceFutureOption.expirationDate) &&
        Objects.equals(this.expirationStyle, referenceFutureOption.expirationStyle) &&
        Objects.equals(this.strikePrice, referenceFutureOption.strikePrice) &&
        Objects.equals(this.underlying, referenceFutureOption.underlying);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractType, description, exchange, exchangeName, multiplier, expirationDate, expirationStyle, strikePrice, underlying);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceFutureOption {\n");
    
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeName: ").append(toIndentedString(exchangeName)).append("\n");
    sb.append("    multiplier: ").append(toIndentedString(multiplier)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    expirationStyle: ").append(toIndentedString(expirationStyle)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    underlying: ").append(toIndentedString(underlying)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
