/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reference data of Index security
 */
@Schema(description = "Reference data of Index security")


public class ReferenceIndex {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("exchange")
  private String exchange = null;

  @JsonProperty("exchangeName")
  private String exchangeName = null;

  public ReferenceIndex description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of Instrument
   * @return description
  **/
  @Schema(example = "DOW JONES 30 INDUSTRIALS", description = "Description of Instrument")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReferenceIndex exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Exchange Code
   * @return exchange
  **/
  @Schema(example = "q", description = "Exchange Code")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ReferenceIndex exchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
    return this;
  }

   /**
   * Exchange Name
   * @return exchangeName
  **/
  @Schema(description = "Exchange Name")
  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceIndex referenceIndex = (ReferenceIndex) o;
    return Objects.equals(this.description, referenceIndex.description) &&
        Objects.equals(this.exchange, referenceIndex.exchange) &&
        Objects.equals(this.exchangeName, referenceIndex.exchangeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, exchange, exchangeName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceIndex {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeName: ").append(toIndentedString(exchangeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
