/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reference data of Equity security
 */
@Schema(description = "Reference data of Equity security")


public class ReferenceEquity {
  @JsonProperty("cusip")
  private String cusip = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("exchange")
  private String exchange = null;

  @JsonProperty("exchangeName")
  private String exchangeName = null;

  @JsonProperty("fsiDesc")
  private String fsiDesc = null;

  @JsonProperty("htbQuantity")
  private Integer htbQuantity = null;

  @JsonProperty("htbRate")
  private Double htbRate = null;

  @JsonProperty("isHardToBorrow")
  private Boolean isHardToBorrow = null;

  @JsonProperty("isShortable")
  private Boolean isShortable = null;

  @JsonProperty("otcMarketTier")
  private String otcMarketTier = null;

  public ReferenceEquity cusip(String cusip) {
    this.cusip = cusip;
    return this;
  }

   /**
   * CUSIP of Instrument
   * @return cusip
  **/
  @Schema(example = "A23456789", description = "CUSIP of Instrument")
  public String getCusip() {
    return cusip;
  }

  public void setCusip(String cusip) {
    this.cusip = cusip;
  }

  public ReferenceEquity description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of Instrument
   * @return description
  **/
  @Schema(example = "Apple Inc. - Common Stock", description = "Description of Instrument")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReferenceEquity exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Exchange Code
   * @return exchange
  **/
  @Schema(example = "q", description = "Exchange Code")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ReferenceEquity exchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
    return this;
  }

   /**
   * Exchange Name
   * @return exchangeName
  **/
  @Schema(description = "Exchange Name")
  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }

  public ReferenceEquity fsiDesc(String fsiDesc) {
    this.fsiDesc = fsiDesc;
    return this;
  }

   /**
   * FSI Desc
   * @return fsiDesc
  **/
  @Schema(description = "FSI Desc")
  public String getFsiDesc() {
    return fsiDesc;
  }

  public void setFsiDesc(String fsiDesc) {
    this.fsiDesc = fsiDesc;
  }

  public ReferenceEquity htbQuantity(Integer htbQuantity) {
    this.htbQuantity = htbQuantity;
    return this;
  }

   /**
   * Hard to borrow quantity.
   * @return htbQuantity
  **/
  @Schema(example = "100", description = "Hard to borrow quantity.")
  public Integer getHtbQuantity() {
    return htbQuantity;
  }

  public void setHtbQuantity(Integer htbQuantity) {
    this.htbQuantity = htbQuantity;
  }

  public ReferenceEquity htbRate(Double htbRate) {
    this.htbRate = htbRate;
    return this;
  }

   /**
   * Hard to borrow rate.
   * @return htbRate
  **/
  @Schema(example = "4.5", description = "Hard to borrow rate.")
  public Double getHtbRate() {
    return htbRate;
  }

  public void setHtbRate(Double htbRate) {
    this.htbRate = htbRate;
  }

  public ReferenceEquity isHardToBorrow(Boolean isHardToBorrow) {
    this.isHardToBorrow = isHardToBorrow;
    return this;
  }

   /**
   * is Hard to borrow security.
   * @return isHardToBorrow
  **/
  @Schema(example = "false", description = "is Hard to borrow security.")
  public Boolean isIsHardToBorrow() {
    return isHardToBorrow;
  }

  public void setIsHardToBorrow(Boolean isHardToBorrow) {
    this.isHardToBorrow = isHardToBorrow;
  }

  public ReferenceEquity isShortable(Boolean isShortable) {
    this.isShortable = isShortable;
    return this;
  }

   /**
   * is shortable security.
   * @return isShortable
  **/
  @Schema(example = "false", description = "is shortable security.")
  public Boolean isIsShortable() {
    return isShortable;
  }

  public void setIsShortable(Boolean isShortable) {
    this.isShortable = isShortable;
  }

  public ReferenceEquity otcMarketTier(String otcMarketTier) {
    this.otcMarketTier = otcMarketTier;
    return this;
  }

   /**
   * OTC Market Tier
   * @return otcMarketTier
  **/
  @Schema(description = "OTC Market Tier")
  public String getOtcMarketTier() {
    return otcMarketTier;
  }

  public void setOtcMarketTier(String otcMarketTier) {
    this.otcMarketTier = otcMarketTier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceEquity referenceEquity = (ReferenceEquity) o;
    return Objects.equals(this.cusip, referenceEquity.cusip) &&
        Objects.equals(this.description, referenceEquity.description) &&
        Objects.equals(this.exchange, referenceEquity.exchange) &&
        Objects.equals(this.exchangeName, referenceEquity.exchangeName) &&
        Objects.equals(this.fsiDesc, referenceEquity.fsiDesc) &&
        Objects.equals(this.htbQuantity, referenceEquity.htbQuantity) &&
        Objects.equals(this.htbRate, referenceEquity.htbRate) &&
        Objects.equals(this.isHardToBorrow, referenceEquity.isHardToBorrow) &&
        Objects.equals(this.isShortable, referenceEquity.isShortable) &&
        Objects.equals(this.otcMarketTier, referenceEquity.otcMarketTier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cusip, description, exchange, exchangeName, fsiDesc, htbQuantity, htbRate, isHardToBorrow, isShortable, otcMarketTier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceEquity {\n");
    
    sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeName: ").append(toIndentedString(exchangeName)).append("\n");
    sb.append("    fsiDesc: ").append(toIndentedString(fsiDesc)).append("\n");
    sb.append("    htbQuantity: ").append(toIndentedString(htbQuantity)).append("\n");
    sb.append("    htbRate: ").append(toIndentedString(htbRate)).append("\n");
    sb.append("    isHardToBorrow: ").append(toIndentedString(isHardToBorrow)).append("\n");
    sb.append("    isShortable: ").append(toIndentedString(isShortable)).append("\n");
    sb.append("    otcMarketTier: ").append(toIndentedString(otcMarketTier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
