/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.marketdata.model.ContractType;
import com.kcjmowright.schwab.marketdata.model.ExerciseType;
import com.kcjmowright.schwab.marketdata.model.ExpirationType;
import com.kcjmowright.schwab.marketdata.model.SettlementType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reference data of Option security
 */
@Schema(description = "Reference data of Option security")


public class ReferenceOption {
  @JsonProperty("contractType")
  private ContractType contractType = null;

  @JsonProperty("cusip")
  private String cusip = null;

  @JsonProperty("daysToExpiration")
  private Integer daysToExpiration = null;

  @JsonProperty("deliverables")
  private String deliverables = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("exchange")
  private String exchange = "o";

  @JsonProperty("exchangeName")
  private String exchangeName = null;

  @JsonProperty("exerciseType")
  private ExerciseType exerciseType = null;

  @JsonProperty("expirationDay")
  private Integer expirationDay = null;

  @JsonProperty("expirationMonth")
  private Integer expirationMonth = null;

  @JsonProperty("expirationType")
  private ExpirationType expirationType = null;

  @JsonProperty("expirationYear")
  private Integer expirationYear = null;

  @JsonProperty("isPennyPilot")
  private Boolean isPennyPilot = null;

  @JsonProperty("lastTradingDay")
  private Long lastTradingDay = null;

  @JsonProperty("multiplier")
  private Double multiplier = null;

  @JsonProperty("settlementType")
  private SettlementType settlementType = null;

  @JsonProperty("strikePrice")
  private Double strikePrice = null;

  @JsonProperty("underlying")
  private String underlying = null;

  public ReferenceOption contractType(ContractType contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  @Schema(description = "")
  public ContractType getContractType() {
    return contractType;
  }

  public void setContractType(ContractType contractType) {
    this.contractType = contractType;
  }

  public ReferenceOption cusip(String cusip) {
    this.cusip = cusip;
    return this;
  }

   /**
   * CUSIP of Instrument
   * @return cusip
  **/
  @Schema(example = "0AMZN.TK12300000", description = "CUSIP of Instrument")
  public String getCusip() {
    return cusip;
  }

  public void setCusip(String cusip) {
    this.cusip = cusip;
  }

  public ReferenceOption daysToExpiration(Integer daysToExpiration) {
    this.daysToExpiration = daysToExpiration;
    return this;
  }

   /**
   * Days to Expiration
   * @return daysToExpiration
  **/
  @Schema(example = "94", description = "Days to Expiration")
  public Integer getDaysToExpiration() {
    return daysToExpiration;
  }

  public void setDaysToExpiration(Integer daysToExpiration) {
    this.daysToExpiration = daysToExpiration;
  }

  public ReferenceOption deliverables(String deliverables) {
    this.deliverables = deliverables;
    return this;
  }

   /**
   * Unit of trade
   * @return deliverables
  **/
  @Schema(example = "$6024.37 cash in lieu of shares, 212 shares of AZN", description = "Unit of trade")
  public String getDeliverables() {
    return deliverables;
  }

  public void setDeliverables(String deliverables) {
    this.deliverables = deliverables;
  }

  public ReferenceOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of Instrument
   * @return description
  **/
  @Schema(example = "AMZN Aug 20 2021 2300 Put", description = "Description of Instrument")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ReferenceOption exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Exchange Code
   * @return exchange
  **/
  @Schema(description = "Exchange Code")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ReferenceOption exchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
    return this;
  }

   /**
   * Exchange Name
   * @return exchangeName
  **/
  @Schema(description = "Exchange Name")
  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }

  public ReferenceOption exerciseType(ExerciseType exerciseType) {
    this.exerciseType = exerciseType;
    return this;
  }

   /**
   * Get exerciseType
   * @return exerciseType
  **/
  @Schema(description = "")
  public ExerciseType getExerciseType() {
    return exerciseType;
  }

  public void setExerciseType(ExerciseType exerciseType) {
    this.exerciseType = exerciseType;
  }

  public ReferenceOption expirationDay(Integer expirationDay) {
    this.expirationDay = expirationDay;
    return this;
  }

   /**
   * Expiration Day
   * minimum: 1
   * maximum: 31
   * @return expirationDay
  **/
  @Schema(example = "20", description = "Expiration Day")
  public Integer getExpirationDay() {
    return expirationDay;
  }

  public void setExpirationDay(Integer expirationDay) {
    this.expirationDay = expirationDay;
  }

  public ReferenceOption expirationMonth(Integer expirationMonth) {
    this.expirationMonth = expirationMonth;
    return this;
  }

   /**
   * Expiration Month
   * minimum: 1
   * maximum: 12
   * @return expirationMonth
  **/
  @Schema(example = "8", description = "Expiration Month")
  public Integer getExpirationMonth() {
    return expirationMonth;
  }

  public void setExpirationMonth(Integer expirationMonth) {
    this.expirationMonth = expirationMonth;
  }

  public ReferenceOption expirationType(ExpirationType expirationType) {
    this.expirationType = expirationType;
    return this;
  }

   /**
   * Get expirationType
   * @return expirationType
  **/
  @Schema(description = "")
  public ExpirationType getExpirationType() {
    return expirationType;
  }

  public void setExpirationType(ExpirationType expirationType) {
    this.expirationType = expirationType;
  }

  public ReferenceOption expirationYear(Integer expirationYear) {
    this.expirationYear = expirationYear;
    return this;
  }

   /**
   * Expiration Year
   * @return expirationYear
  **/
  @Schema(example = "2021", description = "Expiration Year")
  public Integer getExpirationYear() {
    return expirationYear;
  }

  public void setExpirationYear(Integer expirationYear) {
    this.expirationYear = expirationYear;
  }

  public ReferenceOption isPennyPilot(Boolean isPennyPilot) {
    this.isPennyPilot = isPennyPilot;
    return this;
  }

   /**
   * Is this contract part of the Penny Pilot program
   * @return isPennyPilot
  **/
  @Schema(example = "true", description = "Is this contract part of the Penny Pilot program")
  public Boolean isIsPennyPilot() {
    return isPennyPilot;
  }

  public void setIsPennyPilot(Boolean isPennyPilot) {
    this.isPennyPilot = isPennyPilot;
  }

  public ReferenceOption lastTradingDay(Long lastTradingDay) {
    this.lastTradingDay = lastTradingDay;
    return this;
  }

   /**
   * milliseconds since epoch
   * @return lastTradingDay
  **/
  @Schema(example = "1629504000000", description = "milliseconds since epoch")
  public Long getLastTradingDay() {
    return lastTradingDay;
  }

  public void setLastTradingDay(Long lastTradingDay) {
    this.lastTradingDay = lastTradingDay;
  }

  public ReferenceOption multiplier(Double multiplier) {
    this.multiplier = multiplier;
    return this;
  }

   /**
   * Option multiplier
   * @return multiplier
  **/
  @Schema(example = "100", description = "Option multiplier")
  public Double getMultiplier() {
    return multiplier;
  }

  public void setMultiplier(Double multiplier) {
    this.multiplier = multiplier;
  }

  public ReferenceOption settlementType(SettlementType settlementType) {
    this.settlementType = settlementType;
    return this;
  }

   /**
   * Get settlementType
   * @return settlementType
  **/
  @Schema(description = "")
  public SettlementType getSettlementType() {
    return settlementType;
  }

  public void setSettlementType(SettlementType settlementType) {
    this.settlementType = settlementType;
  }

  public ReferenceOption strikePrice(Double strikePrice) {
    this.strikePrice = strikePrice;
    return this;
  }

   /**
   * Strike Price
   * @return strikePrice
  **/
  @Schema(example = "2300", description = "Strike Price")
  public Double getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(Double strikePrice) {
    this.strikePrice = strikePrice;
  }

  public ReferenceOption underlying(String underlying) {
    this.underlying = underlying;
    return this;
  }

   /**
   * A company, index or fund name
   * @return underlying
  **/
  @Schema(example = "AMZN Aug 20 2021 2300 Put", description = "A company, index or fund name")
  public String getUnderlying() {
    return underlying;
  }

  public void setUnderlying(String underlying) {
    this.underlying = underlying;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceOption referenceOption = (ReferenceOption) o;
    return Objects.equals(this.contractType, referenceOption.contractType) &&
        Objects.equals(this.cusip, referenceOption.cusip) &&
        Objects.equals(this.daysToExpiration, referenceOption.daysToExpiration) &&
        Objects.equals(this.deliverables, referenceOption.deliverables) &&
        Objects.equals(this.description, referenceOption.description) &&
        Objects.equals(this.exchange, referenceOption.exchange) &&
        Objects.equals(this.exchangeName, referenceOption.exchangeName) &&
        Objects.equals(this.exerciseType, referenceOption.exerciseType) &&
        Objects.equals(this.expirationDay, referenceOption.expirationDay) &&
        Objects.equals(this.expirationMonth, referenceOption.expirationMonth) &&
        Objects.equals(this.expirationType, referenceOption.expirationType) &&
        Objects.equals(this.expirationYear, referenceOption.expirationYear) &&
        Objects.equals(this.isPennyPilot, referenceOption.isPennyPilot) &&
        Objects.equals(this.lastTradingDay, referenceOption.lastTradingDay) &&
        Objects.equals(this.multiplier, referenceOption.multiplier) &&
        Objects.equals(this.settlementType, referenceOption.settlementType) &&
        Objects.equals(this.strikePrice, referenceOption.strikePrice) &&
        Objects.equals(this.underlying, referenceOption.underlying);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractType, cusip, daysToExpiration, deliverables, description, exchange, exchangeName, exerciseType, expirationDay, expirationMonth, expirationType, expirationYear, isPennyPilot, lastTradingDay, multiplier, settlementType, strikePrice, underlying);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceOption {\n");
    
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
    sb.append("    daysToExpiration: ").append(toIndentedString(daysToExpiration)).append("\n");
    sb.append("    deliverables: ").append(toIndentedString(deliverables)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    exchangeName: ").append(toIndentedString(exchangeName)).append("\n");
    sb.append("    exerciseType: ").append(toIndentedString(exerciseType)).append("\n");
    sb.append("    expirationDay: ").append(toIndentedString(expirationDay)).append("\n");
    sb.append("    expirationMonth: ").append(toIndentedString(expirationMonth)).append("\n");
    sb.append("    expirationType: ").append(toIndentedString(expirationType)).append("\n");
    sb.append("    expirationYear: ").append(toIndentedString(expirationYear)).append("\n");
    sb.append("    isPennyPilot: ").append(toIndentedString(isPennyPilot)).append("\n");
    sb.append("    lastTradingDay: ").append(toIndentedString(lastTradingDay)).append("\n");
    sb.append("    multiplier: ").append(toIndentedString(multiplier)).append("\n");
    sb.append("    settlementType: ").append(toIndentedString(settlementType)).append("\n");
    sb.append("    strikePrice: ").append(toIndentedString(strikePrice)).append("\n");
    sb.append("    underlying: ").append(toIndentedString(underlying)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
