/*
 * Market Data
 * Trader API - Market data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.marketdata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Market info of security
 */
@Schema(description = "Market info of security")


public class RegularMarket {
  @JsonProperty("regularMarketLastPrice")
  private Double regularMarketLastPrice = null;

  @JsonProperty("regularMarketLastSize")
  private Integer regularMarketLastSize = null;

  @JsonProperty("regularMarketNetChange")
  private Double regularMarketNetChange = null;

  @JsonProperty("regularMarketPercentChange")
  private Double regularMarketPercentChange = null;

  @JsonProperty("regularMarketTradeTime")
  private Long regularMarketTradeTime = null;

  public RegularMarket regularMarketLastPrice(Double regularMarketLastPrice) {
    this.regularMarketLastPrice = regularMarketLastPrice;
    return this;
  }

   /**
   * Regular market last price
   * @return regularMarketLastPrice
  **/
  @Schema(example = "124.85", description = "Regular market last price")
  public Double getRegularMarketLastPrice() {
    return regularMarketLastPrice;
  }

  public void setRegularMarketLastPrice(Double regularMarketLastPrice) {
    this.regularMarketLastPrice = regularMarketLastPrice;
  }

  public RegularMarket regularMarketLastSize(Integer regularMarketLastSize) {
    this.regularMarketLastSize = regularMarketLastSize;
    return this;
  }

   /**
   * Regular market last size
   * @return regularMarketLastSize
  **/
  @Schema(example = "51771", description = "Regular market last size")
  public Integer getRegularMarketLastSize() {
    return regularMarketLastSize;
  }

  public void setRegularMarketLastSize(Integer regularMarketLastSize) {
    this.regularMarketLastSize = regularMarketLastSize;
  }

  public RegularMarket regularMarketNetChange(Double regularMarketNetChange) {
    this.regularMarketNetChange = regularMarketNetChange;
    return this;
  }

   /**
   * Regular market net change
   * @return regularMarketNetChange
  **/
  @Schema(example = "-1.42", description = "Regular market net change")
  public Double getRegularMarketNetChange() {
    return regularMarketNetChange;
  }

  public void setRegularMarketNetChange(Double regularMarketNetChange) {
    this.regularMarketNetChange = regularMarketNetChange;
  }

  public RegularMarket regularMarketPercentChange(Double regularMarketPercentChange) {
    this.regularMarketPercentChange = regularMarketPercentChange;
    return this;
  }

   /**
   * Regular market percent change
   * @return regularMarketPercentChange
  **/
  @Schema(example = "-1.1246", description = "Regular market percent change")
  public Double getRegularMarketPercentChange() {
    return regularMarketPercentChange;
  }

  public void setRegularMarketPercentChange(Double regularMarketPercentChange) {
    this.regularMarketPercentChange = regularMarketPercentChange;
  }

  public RegularMarket regularMarketTradeTime(Long regularMarketTradeTime) {
    this.regularMarketTradeTime = regularMarketTradeTime;
    return this;
  }

   /**
   * Regular market trade time in milliseconds since Epoch
   * @return regularMarketTradeTime
  **/
  @Schema(example = "1621368000400", description = "Regular market trade time in milliseconds since Epoch")
  public Long getRegularMarketTradeTime() {
    return regularMarketTradeTime;
  }

  public void setRegularMarketTradeTime(Long regularMarketTradeTime) {
    this.regularMarketTradeTime = regularMarketTradeTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegularMarket regularMarket = (RegularMarket) o;
    return Objects.equals(this.regularMarketLastPrice, regularMarket.regularMarketLastPrice) &&
        Objects.equals(this.regularMarketLastSize, regularMarket.regularMarketLastSize) &&
        Objects.equals(this.regularMarketNetChange, regularMarket.regularMarketNetChange) &&
        Objects.equals(this.regularMarketPercentChange, regularMarket.regularMarketPercentChange) &&
        Objects.equals(this.regularMarketTradeTime, regularMarket.regularMarketTradeTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regularMarketLastPrice, regularMarketLastSize, regularMarketNetChange, regularMarketPercentChange, regularMarketTradeTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegularMarket {\n");
    
    sb.append("    regularMarketLastPrice: ").append(toIndentedString(regularMarketLastPrice)).append("\n");
    sb.append("    regularMarketLastSize: ").append(toIndentedString(regularMarketLastSize)).append("\n");
    sb.append("    regularMarketNetChange: ").append(toIndentedString(regularMarketNetChange)).append("\n");
    sb.append("    regularMarketPercentChange: ").append(toIndentedString(regularMarketPercentChange)).append("\n");
    sb.append("    regularMarketTradeTime: ").append(toIndentedString(regularMarketTradeTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
